### ISSUE TITLE
Controlling requests per second

### ISSUE THREAD

**Issue by Lloople** [spatie/laravel-sitemap#101]
Is there any way to control the max number of requests made per second? Some of the websites I need to generate a Sitemap have a secutiry mod preventing too much requests per second but don't know if I can configure that in laravel-sitemap or even crawler package.

Thanks you and sorry for bad english.

**Comment by freekmurze** [comment]
There isn't on options for that specifically, but there are two things you can do.

1. You can set the [concurreny](https://github.com/spatie/laravel-sitemap/blob/master/src/SitemapGenerator.php#L54-L57) to 1. This will make the crawler only crawl one page at a time.

2. Inside the `CrawlProfile` you give to SiteMapGenerator you could put a `sleep` statement, to slow down crawling.
