### ISSUE TITLE
Call to undefined method Spatie\Sitemap\SitemapGenerator::setMaximumCrawlCount()

### ISSUE THREAD

**Issue by saeedvir** [spatie/laravel-sitemap#108]
when i use this code 

use Spatie\Sitemap\SitemapGenerator;
use Spatie\Crawler\Url;
.
.
.
SitemapGenerator::create('https://example.com')
                                ->setMaximumCrawlCount(500)
                                ->getSitemap();

Error  : 
Call to undefined method Spatie\Sitemap\SitemapGenerator::setMaximumCrawlCount()

**Comment by freekmurze** [comment]
The method is present in the latest version of the package: https://github.com/spatie/laravel-sitemap/blob/3.3.0/src/SitemapGenerator.php#L62

Run `composer update` to pull it in.
