### ISSUE TITLE
Got a composer error during the install 

### ISSUE THREAD

**Issue by polaroi8d** [spatie/laravel-sitemap#109]
On: Ubuntu 16.04.2 LTS

try to install: composer require spatie/laravel-sitemap

Your requirements could not be resolved to an installable set of packages.

Got this error ===> 

>   Problem 1
>     - The requested package phpunit/phpunit == 4.8.35.0 could not be found.
>   Problem 2
>     - Can only install one of: guzzlehttp/guzzle[6.3.0, 6.2.3].
>     - Can only install one of: guzzlehttp/guzzle[6.3.0, 6.2.3].
>     - Can only install one of: guzzlehttp/guzzle[6.3.0, 6.2.3].
>     - spatie/crawler 2.6.0 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0].
>     - spatie/laravel-sitemap 3.3.0 requires spatie/crawler ^2.6 -> satisfiable by spatie/crawler[2.6.0].
>     - Installation request for spatie/laravel-sitemap ^3.3 -> satisfiable by spatie/laravel-sitemap[3.3.0].
>     - Installation request for guzzlehttp/guzzle == 6.2.3.0 -> satisfiable by guzzlehttp/guzzle[6.2.3].
> 
> Potential causes:
>  - A typo in the package name
>  - The package is not available in a stable-enough version according to your minimum-stability setting
>    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
> 
> Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
> 
> Installation failed, reverting ./composer.json to its original content.

I read a lot about the dependencies, and all of it, but can't resolved this conflict.

**Comment by freekmurze** [comment]
Try to install the package into a vanilla Laravel app.

**Comment by scofield-ua** [comment]
@freekmurze what do you mean installing into a vanilla app? What if project already exists?

Currently, I'm getting this error when trying to install the package (`composer require spatie/laravel-sitemap ^2.0`) for Laravel 5.4.36:
```
Problem 1
    - Installation request for spatie/laravel-sitemap 2.0 -> satisfiable by spatie/laravel-sitemap[2.0.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - spatie/laravel-sitemap 2.0.0 requires illuminate/support ~5.3.0 -> satisfiable by illuminate/support[5.3.x-dev, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].
```

Can you please advise?
