### ISSUE TITLE
[QUESTION] How to make this crawler honor robots.txt

### ISSUE THREAD

**Issue by neorganic** [spatie/laravel-sitemap#111]
Is there an option to honor robots.txt file ?

**Comment by freekmurze** [comment]
Out of the box the package doesn't take the `robots.txt` into account when crawling a site.

You can however specify which links should be crawled by providing [your own crawl profile](https://github.com/spatie/laravel-sitemap#define-a-custom-crawl-profile).

In you own crawlprofile you could check for the existance of a `robots.txt`, parse it and determine if the crawled url should be added to the sitemap.
