### ISSUE TITLE
changed site url and package is not creating sitemap

### ISSUE THREAD

**Issue by afrazahmmad** [spatie/laravel-sitemap#113]
I have changed my site url  priority and added www in the url. 
After changing url from https://phone-pedia.com to https://www.phone-pedia.com. Package has stopped generating sitemap.

Cleared cache and config files but issue is still there.

**Comment by freekmurze** [comment]
Could you add a failing test for me to look at?

**Comment by afrazahmmad** [comment]
When I removed www, it worked again. But with www, this package doesn't crawl the. 
I have created a console command to update sitemap. 
with www, console command finished in half second sitemap.xml gets empty.

For now, I am using sitemap without www

**Comment by Akilez** [comment]
@afrazahmmad Are you sure there is no redirect?  **www- to non-www-** If your site does, you might consider turning on ```ALLOW_REDIRECTS```.

    'guzzle_options' => [
         * Describes the redirect behavior of a request.
         */
        RequestOptions::ALLOW_REDIRECTS => true,
    ],

**Comment by nhayder** [comment]
hey, been checking out the page and i'm getting empty sitemap file, 
`
Route::get('/sitemap', function(){
	SitemapGenerator::create('/')->writeToFile('sitemap.txt');
	return 'Sitemap generated';
});
`
this is what i'm getting
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>`

i have robot.txt file configured like this

`User-agent: *
Allow: /
Disallow: /admin`

can anyone see issue with my code? 

any ideas ????
