### ISSUE TITLE
Console command to generate sitemap from conroller shows strange error. 

### ISSUE THREAD

**Issue by afrazahmmad** [spatie/laravel-sitemap#116]
Hello,
I usually update sitemap through create:sitemap command from console and it works perfectly.
But calling the same command from route closure or controller doesn't work and shows this error.
![artisan call error](https://user-images.githubusercontent.com/22490945/34433291-1d840952-eca0-11e7-9752-706994479651.png)
All other commands in controller works except this.  

I have tried,
Route::get('update/sitepam',function(){
           \Artisan::call('create:sitemap');
});
and 

Route::get('update/sitemap','sitemapController@updateSitemap');
and updateSitemap function contains the same code i.e. \Artisan::call('create:sitemap');

**Comment by sebastiandedeyne** [comment]
That dependency requires php 7.1, which your environment doesn't support. Either upgrade your php version, or add a `platform` key to specify the php version.

https://getcomposer.org/doc/06-config.md#platform

**Comment by afrazahmmad** [comment]
My php version is 7.1.11.

**Comment by sebastiandedeyne** [comment]
Your console php version is, but the web version probably isn't, they're two different installations.

**Comment by afrazahmmad** [comment]
Yeah got it. composer.json has 7.0
thanks for poiting out the reason.

**Comment by afrazahmmad** [comment]
What permissions should I give to sitemap.xml  ? 
To run command from controller, its asking for permission.
