### ISSUE TITLE
ignore url with get parameters

### ISSUE THREAD

**Issue by angallego** [spatie/laravel-sitemap#124]
I have url with parameters, for example: http://domain.com/products?page=1

How could I do for ignore this url? Because, it doesn´t appear in `$url->segment(1)`
But http://domain.com/products?category=zoo yes
```
Spatie\Sitemap\Tags\Url Object ( [url] => http://domain.com/products?page=1 [lastModificationDate] => Carbon\Carbon Object ( [date] => 2018-02-07 17:57:50.746171 [timezone_type] => 3 [timezone] => Europe/Madrid ) [changeFrequency] => daily [priority] => 0.8 [alternates] => Array ( ) ) 

path: /products
Segs: products
Seg1: products
Seg2: 
```

**Comment by igerslike** [comment]
Yeah, the crawler is doing this exactly, we need way to ingore the URL parameters from getting crawled as its bad for SEO
