### ISSUE TITLE
Only one URL has been created.

### ISSUE THREAD

**Issue by angallego** [spatie/laravel-sitemap#126]
I'm using the version 2.4.0 for Laravel 5.4.36.
When execute the package in localhost, it's working right, but no works in producction eviroment. It's creating only one URL, the one main url of the site. 

I've test others sites, for example: https://spatie.be/en and this works perfectaly

The same URL I check and run in localhost, does not work in production.

**Comment by freekmurze** [comment]
Could it be that your server detects the crawler and does not respond with the homepage but with something else?

**Comment by vishnoex** [comment]
Greetings,
