### ISSUE TITLE
Sitemap generates urls without slash between route and model

### ISSUE THREAD

**Issue by dilger** [spatie/laravel-sitemap#129]
Hi,

I am creating my sitemap manually, but unfortunately the Url::create() generates locally urls with correct slashes, but online it does not.

Locally:

`http://localhost:3000/de/articles/die-andere-seite-der-grenze`

Online:

`https://[host]/de/articlesdie-andere-seite-der-grenze`

The generating function looks like this:

`$url = Url::create(LaravelLocalization::localizeURL(route('frontend.articles.show', [
                    'article' => $article->slug
                ]), LaravelLocalization::getCurrentLocale()))->setLastModificationDate($article->published_at);`

Any idea how this could be prevented?

Kind regards

Chris

**Comment by dilger** [comment]
If I use the Url::create() function in isolation it does work and generates

`https://[host]/de/articles/die-andere-seite-der-grenze`,

but if used within the sitemap generator it doesn't work. I am wondering, what may be the difference  in context, that may influence that.

Seems like this i more related to the LaravelLocalization package, but not sure. Fixed it for now by check on unslashed strings like 

`articlesdie-andere-seite-der-grenze`

and inserting the necessary slash. Needs further investigation from my side, but can be closed here, I think.

**Comment by cihankusmez** [comment]
This error still exists when we use LaravelLocalization.
