### ISSUE TITLE
[L5.6] Installation conflicts with spatie/laravel-link-checker

### ISSUE THREAD

**Issue by rjsworking** [spatie/laravel-sitemap#130]
Hi. Cannot install spatie/laravel-sitemap after install spatie/laravel-link-checker.
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-sitemap ^4.0 -> satisfiable by spatie/laravel-sitemap[4.0].
    - Conclusion: remove spatie/crawler 2.2.1
    - Conclusion: don't install spatie/crawler 2.2.1
```

spatie/laravel-link-checker requires spatie/crawler: ^2.0.2 but the sitemap package requires spatie/crawler: ^3.0

Cheers

**Comment by freekmurze** [comment]
We'll create a new version of laravel-link-checker soon that uses crawler v3.

**Comment by freekmurze** [comment]
We've released a new version of the laravel-link-checker.

https://github.com/spatie/laravel-link-checker/blob/master/CHANGELOG.md#300---2018-02-12

**Comment by rjsworking** [comment]
Hi. Got the same problem again with a fresh L5.6: spatie/laravel-sitemat v5 requires spatie/crawler 4.0.3 and it conflicts with spatie/laravel-link-checker  v3

```
- Installation request for spatie/laravel-link-checker ^3.0 -> satisfiable by spatie/laravel-link-checker[3.0.0].
- Conclusion: remove spatie/crawler 4.0.3
- Conclusion: don't install spatie/crawler 4.0.3
```

Cheers

**Comment by freekmurze** [comment]
We'll tag a new version that will be compatible with crawler v4 soon.

**Comment by rjsworking** [comment]
It would be nice to have spatie/http-status-check updated too.

Cheers
