### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by weijinnx** [spatie/laravel-sitemap#131]
Hey! I have 5.6 instance. So, how to create full sitemap? For now, when I create it, in sitemap file I have only 1 url (main). But I have routes, like blogs, blogs/{slug} and others. How can I crawl those urls too?

Thanks!

**Comment by freekmurze** [comment]
The readme contains an example: https://github.com/spatie/laravel-sitemap#generating-a-sitemap

Make sure a request to the url you pass to `create` responds with html. If you do not see all the links you expect in the sitemap it could be that your server detects a crawler and maybe serves up differnt response from the one you're expecting.
