### ISSUE TITLE
[L5.6] Update Failure on L5.6

### ISSUE THREAD

**Issue by littpi** [spatie/laravel-sitemap#132]
Hello.

I have tried to update Laravel to 5.6 and there is a problem occurred with following.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.2
    - Conclusion: don't install laravel/framework v5.6.1
    - spatie/laravel-sitemap 3.3.1 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - spatie/laravel-sitemap 3.2.0 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - spatie/laravel-sitemap 3.2.1 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - spatie/laravel-sitemap 3.2.2 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - spatie/laravel-sitemap 3.3.0 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - spatie/laravel-sitemap 3.3.1 requires illuminate/support ~5.5.0 -> satisfiable by laravel/framework[v5.5.34], illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - Can only install one of: laravel/framework[v5.6.0, v5.5.34].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.0
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.6.0
    - Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[v5.6.0, v5.6.1, v5.6.2, v5.6.3].
    - Installation request for spatie/laravel-sitemap ^3.2 -> satisfiable by spatie/laravel-sitemap[3.2.0, 3.2.1, 3.2.2, 3.3.0, 3.3.1].

How can I solve this problem?

**Comment by TVke** [comment]
Hey @littpi 

there is a new major version released of `spatie/laravel-sitemap` (4.0) with laravel 5.6 support.

Hope this helps.
