### ISSUE TITLE
Do official crawprofiles not work anymore?

### ISSUE THREAD

**Issue by tmoldri** [spatie/laravel-sitemap#133]
When i installed the package (few weeks back) it said in the readme that this package comes with custom crawlprofiles, one of them is CrawlSubdomains to make crawler crawl sobdomains too and i configured site to use this just like it said in the readme. But the subdomains are not crawled. And now i cant find any mention on it in the readme.

I am using Laravel 5.5.

Is this no longer working?

**Comment by freekmurze** [comment]
It's still there: the `CrawlSubdomains` class is part of the crawler: https://github.com/spatie/crawler/blob/master/src/CrawlSubdomains.php

**Comment by freekmurze** [comment]
If this doesn't work for you, feel free to open a PR.

**Comment by tmoldri** [comment]
Oh yeah, I must have mixed up these packages in my mind, my bad. But yes, i put CrawlSubdomains::class to config but subdomain links in the footer are not crawled. There are no errors.

**Comment by tmoldri** [comment]
Thank you very much for your time and effort, will do! @TVke
