### ISSUE TITLE
Incorrect instance of passed to 

### ISSUE THREAD

**Issue by maiolica** [spatie/laravel-sitemap#134]
Hello, I've upgraded from Laravel 5.5 to Laravel 5.6, and laravel-sitemap to version 4.0.
When running the custom command `php artisan sitemap:generate` this error pops up:

```
Type error: Argument 1 passed to App\Console\Commands\GenerateSitemap::App\Console\Commands\{closure}() must be an instance of Spatie\Crawle
  r\Url, instance of GuzzleHttp\Psr7\Uri given, called in C:\xampp\htdocs\bvc\vendor\spatie\laravel-sitemap\src\SitemapGenerator.php on line 1
  35

```

This is the GenerateSitemap command (which was working with Laravel 5.5):

```php

<?php

namespace App\Console\Commands;

use Spatie\Crawler\Url;
use Illuminate\Console\Command;
use Spatie\Sitemap\SitemapGenerator;

class GenerateSitemap extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'sitemap:generate';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate the sitemap.';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        SitemapGenerator::create(config('app.url'))
            ->shouldCrawl(function(Url $url) {
                return $url->segment(1) !== 'image';
            })
            ->writeToFile(public_path('sitemap.xml'));

        $this->info('Sitemap generated.');
    }
}
```

Am I missing something?
Thank you!

**Comment by freekmurze** [comment]
One of the underlying changes is that we now use PSR7 compliant `Url` objects.

You should update your command so the closure works with that object.

**Comment by coatesjonathan** [comment]
@freekmurze what does this mean? any help please? how does the command get updated?

**Comment by keisto** [comment]
Replace `use Spatie\Crawler\Url;` with `use Psr\Http\Message\UriInterface;`

`->shouldCrawl(function(Url $url) {` with `->shouldCrawl(function(UriInterface $url) {`

I just came just came across this, so I hope I helped someone.
