### ISSUE TITLE
Class CrawlProfile cannot extend from interface Spatie\Crawler\CrawlProfile

### ISSUE THREAD

**Issue by Nowi5** [spatie/laravel-sitemap#138]
Hi all,

excuse me that I have to asked, but I was on the way to implement my own profile.
Not sure where to store I made a new class and published it in the config.
When I used your example I got the error: Class App\Src\StiemapCrawlProfile cannot extend from interface Spatie\Crawler\CrawlProfile

So when I see that this is an interface I see that I have to use implements and not extends.
With that I had to adjust the parameters.

Declaration of App\Src\SitemapCrawlProfile::shouldCrawl(App\Src\Uri $url): bool must be compatible with Spatie\Crawler\CrawlProfile::shouldCrawl(Spatie\Crawler\Url $url): bool

When I adjusted that I got another error:
Call to undefined method Spatie\Crawler\Url::getHost()

Maybe you can have a look to your example of an own profile.
For testing this is working:

```
<?php

namespace App\Src;

use Spatie\Crawler\Url;
use Spatie\Crawler\CrawlProfile;

class SitemapCrawlProfile implements CrawlProfile
{
    /**
     * Determine if the given url should be crawled.
     *
     * @param \GuzzleHttp\Psr7\Uri $url
     *
     * @return bool
     */
    public function shouldCrawl(\Spatie\Crawler\Url $url): bool
    {
        var_dump($url);
//        if ($url->getHost() !== 'localhost') { //getHost is unknown
//            return false;
//        }

//        return is_null($url->segment(1));
        return true;
    }
}
```

Thank you very much.

**Comment by freekmurze** [comment]
We recently released a new major version of the crawler that replaced the interfaces with abstract classes. I highly recommend using the latest version. Take a look at the readme for some examples on how to get started.
