### ISSUE TITLE
SelfSigned Certificates HTTPS

### ISSUE THREAD

**Issue by Nowi5** [spatie/laravel-sitemap#139]
Hello,

at least within my staging environment I use a not matching https domain and self signed certificate.
When I run the sitemap script with http everything is fine, but not with https.
Is there a way to disable verify?

 $guzzle->setDefaultOption('verify', false);

Would be grate to have this in the config options.

Thank you.

**Comment by Nowi5** [comment]
I think the answer is here:
https://github.com/guzzle/guzzle/blob/master/src/RequestOptions.php

So to add simple  RequestOptions::VERIFY => false

**Comment by freekmurze** [comment]
Yup, you can add that option in the config file.
