### ISSUE TITLE
Relative paths when using manually created sitemap links

### ISSUE THREAD

**Issue by rikiless** [spatie/laravel-sitemap#141]
If i decide to create sitemap links manually like this way:

```php
Category::all()->each(function (Category $category) {
    $this->sitemap->add(Url::create($category->path()));
});

// $category->path() returns "/category/slug"

```

Output of sitemap.xml is generated with relative links (http protocol and domain name is missing). Do I need to provide absolute paths as arguments into Url::create method?

**Comment by freekmurze** [comment]
Laravel has a helper to make a relative link absolute.

Try this:


```
$this->sitemap->add(Url::create(url($category->path())));
```

**Comment by rikiless** [comment]
ok, thank you.
