### ISSUE TITLE
How to create sitemap.xml.gz

### ISSUE THREAD

**Issue by dev4xy** [spatie/laravel-sitemap#142]
Hi,
How to create sitemap.xml.gz ?
Thanks.

**Comment by freekmurze** [comment]
The readme explains the ways you can create a  `sitemap.xml`. Compressing it `.gz` isn't supported by this package.

**Comment by matijakovacevic** [comment]
@freekmurze Would you be open for a PR about compressing to gzip feature?

**Comment by freekmurze** [comment]
Probably not, unless the code is very simple and well tested.
