### ISSUE TITLE
[Suggestion]   RequestOptions::ALLOW_REDIRECTS => should be true by default

### ISSUE THREAD

**Issue by neorganic** [spatie/laravel-sitemap#150]
From real life practice I can't really think of a lot of cases when the user would like to see the middle redirected path for the sitemap. Generally it's the last path that's wanted. 

Also this would solve the problem when 404 pages are added in the sitemap.

**Comment by freekmurze** [comment]
Changing this now would be a breaking change. I'll revisit this when creating a new major version.
