### ISSUE TITLE
Split into multiple sitemap files

### ISSUE THREAD

**Issue by mdnpro** [spatie/laravel-sitemap#152]
Hi
I'm generating sitemap with a function which you can see [here](https://paste.ofcode.org/nmybtbhTfzVYSzZsNWeRfU).
Now I want to split and generate sitemap files for every 10K posts. How can I do this?Something like this:
posts_sitemap1.xml -> 0-10,000
posts_sitemap2.xml -> 10001-11000
..........

Would you please help me?

**Comment by AlphaGeek509** [comment]
Why did you close your own request.  I, too, have this problem/concern.

**Comment by mdnpro** [comment]
@AlphaGeek509 I found out that this package doesn't support what I am looking for. So I switched to to another package wich support this function very well.
https://github.com/Laravelium/laravel-sitemap?files=1
