### ISSUE TITLE
Auto split sitemap when reaching 50.000 urls

### ISSUE THREAD

**Issue by robindirksen1** [spatie/laravel-sitemap#153]
Is it possible to auto split the sitemap when it collects more than 50.000 urls? This way you don't have to worry about the fact that the sitemap is to big.

Taken from here: https://www.sitemaps.org/protocol.html#index

**Comment by freekmurze** [comment]
Currently this is not possible. For our projects we've never had the need.

If the code is simple and well tested I'd consider accepting a PR that adds this to the package.
