### ISSUE TITLE
noindex still included on sitemap

### ISSUE THREAD

**Issue by garygreen** [spatie/laravel-sitemap#156]
Currently when the crawler comes across pages with:

```html
<meta name="robots" content="noindex, follow">
```

It will still index those pages and add them to the sitemap. When you attempt to add a sitemap with noindexed pages on Google Webmaster tools it warns you:

![image](https://user-images.githubusercontent.com/1702638/39309528-2881d560-4960-11e8-9fb5-eff21143c616.png)

It says "robots.txt" but here it's referring to the `noindex` flag really.

What's the correct behaviour here? Shouldn't the crawler exclude those links or at least have an option to exclude ones which match in robots.txt/have no index flag?

**Comment by freekmurze** [comment]
We will soon implement [our robots-txt package](https://github.com/spatie/robots-txt) into the crawler that is used under the hood of laravel-sitemap.

That'll fix this issue.

ETA: a few weeks / months.

**Comment by brendt** [comment]
As of 5.2.0, robot checks are supported by default: https://github.com/spatie/laravel-sitemap/releases/tag/5.2.0
