### ISSUE TITLE
xml stylesheet

### ISSUE THREAD

**Issue by gerrybarron** [spatie/laravel-sitemap#162]
Hi, I tried modifying the sitemap.blade.php and added this line of code
![image](https://user-images.githubusercontent.com/15038452/39555600-0c5954ba-4ead-11e8-9346-a0395edbf871.png)
but it doesn't work. I don't know if this is possible to add this or there is a workaround
![image](https://user-images.githubusercontent.com/15038452/39555573-ce24f9ce-4eac-11e8-93ea-dd71054b04d8.png)

![image](https://user-images.githubusercontent.com/15038452/39555564-bc709b98-4eac-11e8-9053-b71d9cd8929c.png)

I just want to know if its possible to add a stylesheet on the sitemap using laravel-sitemap.

**Reference link:**
https://github.com/pedroborges/xml-sitemap-stylesheet

**Comment by freekmurze** [comment]
We use [this view](https://github.com/spatie/laravel-sitemap/blob/master/resources/views/sitemap.blade.php) to render the sitemap. 

I'd accept a PR that would publish this view so the view can be modified by users of the package.

**Comment by VincentKos** [comment]
That's already the case no ? It publish the whole view folder

**Comment by freekmurze** [comment]
If you publish the view files provided to this package, you can customize the sitemap to your heart’s content.
