### ISSUE TITLE
use Spatie\Crawler\Url; doesn't exist?

### ISSUE THREAD

**Issue by elfeffe** [spatie/laravel-sitemap#167]
I'm receiving the error that class use Spatie\Crawler\Url doesn't exist.
It has been removed?

**Comment by brendt** [comment]
`Url` has been removed in `spatie/crawler ^3.0`.

More information can be found in the changelog: https://github.com/spatie/laravel-sitemap/blob/master/UPGRADING.md#from-30-to-40
