### ISSUE TITLE
Maximum Crawl Depth?

### ISSUE THREAD

**Issue by agentmarine** [spatie/laravel-sitemap#175]
Is there a way to generate a site map with a maximum crawl depth?

for example

```
home
about
categories
    -cat1
        -prod1
        -prod2
    -cat2
        -prod3

```

say I only want to go 1 level deep, so i can go Categories & Cat1, Cat2, but not go deeper into Prod1?
This is just an example, I wont always know the depth of the site, but to limit extremely large sitemaps being generated need a way to restrict it to only the top two or so levels of the tree.

**Comment by freekmurze** [comment]
You can configure the crawl depth on the crawler itself. Here we set a maximum depth of 3:

```php
SitemapGenerator::create($yourUrl)
    ->configureCrawler(function (Crawler $crawler) {
        $crawler->setMaximumDepth(3)
    })
    ->writeToFile($file);
```
