### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by veneliniliev** [spatie/laravel-sitemap#177]
i can't install package with laravel 5.5

 Problem 1
    - Installation request for spatie/laravel-sitemap 5.1.0 -> satisfiable by spatie/laravel-sitemap[5.1.0].
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - spatie/laravel-sitemap 5.1.0 requires spatie/crawler ^4.0.3 -> satisfiable by spatie/crawler[4.0.3, 4.0.4, 4.0.5, 4.1.0, v4.x-dev].
    - spatie/crawler 4.0.3 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.4,
v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/crawler 4.0.4 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.4,
v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/crawler 4.0.5 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.4,
v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/crawler 4.1.0 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.4,
v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - spatie/crawler v4.x-dev requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.
4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/support v5.6.0|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.1|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.2|don't install laravel/framework v5.5.40
    - don't install illuminate/support v5.6.3|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.0|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.11|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.12|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.13|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.14|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.15|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.16|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.17|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.18|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.19|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.20|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.21|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.4|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.5|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.6|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.7|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.8|don't install laravel/framework v5.5.40
    - don't install tightenco/collect v5.6.9|don't install laravel/framework v5.5.40
    - Installation request for laravel/framework (locked at v5.5.40, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.40].

**Comment by ngugijames** [comment]
Same here.

**Comment by freekmurze** [comment]
Can you upgrade to Laravel 5.6?

**Comment by veneliniliev** [comment]
install old version fix problem

`composer install spatie/laravel-sitemap 4.0`

is not the best solution but work!

**Comment by visualcom** [comment]
@freekmurze unfortunately can't upgrade to Laravel 5.6 in our case... is spatie/laravel-sitemap 4.0 the best compatible alternative for Laravel 5.5?
thank you, spatie packages are very usefull and high quality packages :)

**Comment by freekmurze** [comment]
v4 should work with Laravel 5.5 indeed: https://github.com/spatie/laravel-sitemap/blob/4.0/composer.json#L20

**Comment by GoldChess** [comment]
> install old version fix problem
> 
> `composer install spatie/laravel-sitemap 4.0`
> 
> is not the best solution but work!

composer require spatie/laravel-sitemap:4.0

This is True Command
