### ISSUE TITLE
i cant install this package :(

### ISSUE THREAD

**Issue by parsa-script** [spatie/laravel-sitemap#178]
every time i try to install it i give this error :
    - Installation request for spatie/laravel-sitemap ^5.2 -> satisfiable by spatie/laravel-sitemap[5.2.0].

**Comment by parsa-script** [comment]
my laravel version is 5.5

**Comment by sebastiandedeyne** [comment]
Could you try installing version `^3.0` instead?

**Comment by parsa-script** [comment]
thanks a lot :)
