### ISSUE TITLE
Generates empty sitemap on Laravel 5.6

### ISSUE THREAD

**Issue by felixgoldstein** [spatie/laravel-sitemap#179]
Any idea how to fix it?

**Comment by aurawindsurfing** [comment]
The same on my end. It just created:

`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>
`

**Comment by freekmurze** [comment]
Probably the crawler can't find any links on the your homepage. Try requesting the entry point of your site with curl.

**Comment by felixgoldstein** [comment]
Sorry was my bad, my robots.txt disallowed unknown crawlers. Using the `$crawler->ignoreRobots();` setting solved it for me.

**Comment by sergeevpasha** [comment]
that didn't help, i don't even have robots.txt, is there any other possible solutions?
