### ISSUE TITLE
Not working in laravel 5.5

### ISSUE THREAD

**Issue by karandeepsinghexpert** [spatie/laravel-sitemap#180]
![screenshot from 2018-07-03 15-22-56](https://user-images.githubusercontent.com/26301828/42212897-09926278-7ed5-11e8-9f11-21efb2385ef9.png)
When I try to install this component it throws an error however it installed successfully in laravel version 5.6,
Can You please let me know why it is not working in 5.5?

**Comment by techn0guy** [comment]
I am also receiving the error in 5.5

**Comment by brendt** [comment]
I'll look into this at the end of this week.

**Comment by RobLui** [comment]
Any updates on this issue yet? Having this issue here too while trying to look into using the package :) @brendt

**Comment by brendt** [comment]
Pretty swamped with project work at the moment. It's on my todo but I can't guarantee I'll be able to look into it this week. 

A quick tip if you want to debug, you can use `composer why-not spatie/laravel-sitemap` to know what package is causing the conflict.

**Comment by RobLui** [comment]
Ok dw, thanks. :)

**Comment by Stretsh** [comment]
Seems like `spatie/crawler 4.1.x` is the culprit, requiring `tightenco/collect ^5.6`

> - spatie/laravel-sitemap 5.2.0 requires spatie/crawler ^4.1.0 -> satisfiable by spatie/crawler[4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6].
>     - spatie/crawler 4.1.0 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.1 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.2 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.3 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.4 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.5 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
>     - spatie/crawler 4.1.6 requires tightenco/collect ^5.6 -> satisfiable by illuminate/support[v5.6.0, v5.6.1, v5.6.2, v5.6.3], tightenco/collect[v5.6.0, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.27, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].

**Comment by Stretsh** [comment]
I do wonder though why this is not backwards compatible with the latest LTS version of Laravel (5.5), since most devs would use that for long term projects...

**Comment by freekmurze** [comment]
We don't value LTS that much for our projects, so in our packages we don't mind requiring dependencies that are newer than LTS.

More info: https://murze.be/laravel-lts-is-a-trap

**Comment by brendt** [comment]
@Stretsh as Freek already said, we don't value LTS and old upgrades very much. At Spatie we feel the 
shared responsibility to help keep the community up-to-date. This is why most of our packages target only the latest versions of Laravel and PHP.

I understand it's not always as trivial to perform upgrades; but sooner or later, you'll have to anyways. My recommendation is to upgrade to L5.6. Here's the migration guide: https://laravel.com/docs/5.6/upgrade

If you're absolutely stuck on L5.5, and in the need for this package, you're always free to fork and maintain your own version.
