### ISSUE TITLE
not crawler some page

### ISSUE THREAD

**Issue by hekmatinasser** [spatie/laravel-sitemap#182]
hi
after write in sitemap.xml detected page but not not crawler some link  page paginate.
because in route web.php use middleware throttle:10,1

can set delay in crawler tree?

**Comment by freekmurze** [comment]
There isn't an dedicated method for specifying a delay but you can configure [the underlying crawler](https://github.com/spatie/crawler) with the `configureCrawler` function (there's an example in the readme).

You could create a crawl observer and put a call to `sleep`in the `willCrawl` function. More info in the crawler docs: https://github.com/spatie/crawler#usage
