### ISSUE TITLE
Call to undefined method configureCrawler()

### ISSUE THREAD

**Issue by hekmatinasser** [spatie/laravel-sitemap#183]
after set max depth 10  error Call to undefined method Spatie\Sitemap\SitemapGenerator::configureCrawler()

`        SitemapGenerator::create(config('app.url'))`
`            ->configureCrawler(function (Crawler $crawler) {`
`                $crawler->setMaximumDepth(10);`
`            })`
`            ->writeToFile(public_path('sitemap.xml'));`

**Comment by freekmurze** [comment]
The tests seem to indicate that this function is working properly.

https://github.com/spatie/laravel-sitemap/blob/master/tests/SitemapGeneratorTest.php#L119-L129

If the problem persists, could you PR a failing test?
