### ISSUE TITLE
url like "https://domain/../" writen on my generated sitemap

### ISSUE THREAD

**Issue by minhtudapp** [spatie/laravel-sitemap#184]
I have used your sitemap generator and it works quite well, except some url(s) written in the sitemap has the structure like "https://domain/../", and some has craw error (not found). I have search for pages which contain these links but I have found nothing. My website use 99% relative URL. I don't know where to find the causes. Can you give me some advises with explanation?

My website: https://skyenter.vn
My sitemap: https://skyenter.vn/sitemap.xml

Thanks!

**Comment by minhtudapp** [comment]
Is there a way to find and show where the url found from. If there is, it will be great for having right solutions! Many thanks!

**Comment by freekmurze** [comment]
You can determine where the url was found here: https://github.com/spatie/laravel-sitemap/blob/837ede09edc08678f1bd1c0ad7bfc0b0c767961d/src/Crawler/Observer.php#L46

**Comment by minhtudapp** [comment]
Thank for your advice, i'll try to make the sitemap show urls with parent one!
