### ISSUE TITLE
Command not automatically registered

### ISSUE THREAD

**Issue by chrisjohnstone** [spatie/laravel-sitemap#186]
This issue could well be down to my individual app but after installation (using L5.6), generating a command (`php artisan make:command GenerateSitemap`) and adding it to the `schedule` method in my `Kernel.php`, I found I wasn't able to run the command from the CLI.

After adding updating my `Kernel.php` to:

```
...
protected $commands = [
        Commands\GenerateSitemap::class
    ];
...
```

I can now see the command listed in `php artisan list`.

**Comment by freekmurze** [comment]
In modern Laravel app all commands in the default folder will automatically be registered.
