### ISSUE TITLE
how to use it without composer?

### ISSUE THREAD

**Issue by jmar83** [spatie/laravel-sitemap#187]
That code causes this error:

"Parse error: syntax error, unexpected ':', expecting ';' or '{' in C:\xampp\htdocs\testing\laravel-sitemap-master\src\SitemapGenerator.php on line 63"

[CODE]
<?php
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/Sitemap.php';
require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapGenerator.php';
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapIndex.php';
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapServiceProvider.php';

use Spatie\Sitemap\SitemapGenerator;

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */
 

// Remove trailing slash from uri!!
if(($_SERVER['REQUEST_URI'] != "/") && preg_match('{/$}', $_SERVER['REQUEST_URI'])) {
    header('Location: '.preg_replace('{/$}', '', $_SERVER['REQUEST_URI']));
    exit;
}

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require  $_SERVER ['DOCUMENT_ROOT'].'/bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once $_SERVER ['DOCUMENT_ROOT'].'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

if(isset($_GET['generateSitemap']))
{
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
    
    // echo "test";
    
    
    exit;
}

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

[/CODE]

I want to use it in /index.php (laravel application entry point), so i can call /index.php?generateSitemap to (re-)generate the sitemap.

The laravel version i use it 5.4.x, maybe it's too old?

Best regards,
Jan

**Comment by jmar83** [comment]
Code well-formatted:

`<?php
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/Sitemap.php';
require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapGenerator.php';
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapIndex.php';
//require_once $_SERVER['DOCUMENT_ROOT'].'/testing/laravel-sitemap-master/src/SitemapServiceProvider.php';


use Spatie\Sitemap\SitemapGenerator;

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */
 

// Remove trailing slash from uri!!
if(($_SERVER['REQUEST_URI'] != "/") && preg_match('{/$}', $_SERVER['REQUEST_URI'])) {
    header('Location: '.preg_replace('{/$}', '', $_SERVER['REQUEST_URI']));
    exit;
}

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require  $_SERVER ['DOCUMENT_ROOT'].'/bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once $_SERVER ['DOCUMENT_ROOT'].'/bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

if(isset($_GET['generateSitemap']))
{
    ini_set('display_errors', 1);
    ini_set('display_startup_errors', 1);
    error_reporting(E_ALL);
    
    // echo "test";
    
    
    exit;
}

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
`

**Comment by freekmurze** [comment]
Make sure you have the PHP 7 or higher installed.
