### ISSUE TITLE
Ignore URL with Query and Parameters + Prevent Duplicates

### ISSUE THREAD

**Issue by igerslike** [spatie/laravel-sitemap#188]
There are 2 important  issues:

- The crawler should have the track of what URLs have been scrapped on an array/we and perform an array filter before writing them out. This way would prevent duplicate links into the XML
- The crawler is not smart enough to detect URLs with query or parameters on the URL and ignore them as it's not SEO friendly to have URLs in sitemap with Query Strings, they are not relevant to Google's eyes, as an alternative, we should add a method/config to ignore those URLs

A temporary solution into ignoring URL with queries could be 

```
->hasCrawled(function (Url $url) {
    # Ignore if URL is not canonical
    if(strpos($url->url, '?') !== false){
        return;
    }
}
```

**Comment by freekmurze** [comment]
> as it's not SEO friendly to have URLs in sitemap with Query Strings

I don't know if this is true in all cases. I can image sites that need those parameters in order to display the right content.

**Comment by igerslike** [comment]
@freekmurze  In any case, this should be an option, to either ignore them or not, this was only my "dirty" hammered fix 🔨 ! hope it helps :D

**Comment by freekmurze** [comment]
Feel free to submit a PR if you want this in the package. Should be implemented with a `CustomCrawlProfile`
