### ISSUE TITLE
Q: Is there an option to see your output before it generated the whole sitemap..?

### ISSUE THREAD

**Issue by RobLui** [spatie/laravel-sitemap#189]
On smaller sites sitemap generation is no problem, but from the moment it becomes a bigger site with +500 pages .. it seems to always lock up ..
Made a 'tool' to generate sitemaps for other sites by just inputting an url..
Like the ones do on the i'net with max 500 pages.. 

so I'd like to know if it even generates something or nothing at all?

thanks in advance
R

**Comment by freekmurze** [comment]
> so I'd like to know if it even generates something or nothing at all?

The package doesn't contain any functionality for that. You need to check it yourself. 

If you find that the problems are caused by a bug in this package, feel free to submit a PR.
