### ISSUE TITLE
Exclude some URLs not working

### ISSUE THREAD

**Issue by AmazingVanish** [spatie/laravel-sitemap#192]
The ReadMe is horribly out of date with references to \Spatie\Crwaler\Url all over. Since you upgrade to using PSR none of those directions work anymore.

How do I exclude some urls using the PSR Uri? segment() is not a method on that class.

**Comment by freekmurze** [comment]
We'll update the readme soon!

**Comment by brendt** [comment]
I've updated the examples in the README. 

@AmazingVanish PSR-7 doesn't have a `segment` helper, so you'll either have to use an `strpos` check, or something like this.

```php
[$firstSegment] = explode('/', $url->getPath());

return $firstSegment === 'contact';
```

Please see the official PSR-7 spec for more information: https://www.php-fig.org/psr/psr-7/

Also, don't hesitate to send a PR if you discover any more issues, thanks.
