### ISSUE TITLE
Empty sitemap

### ISSUE THREAD

**Issue by sergeevpasha** [spatie/laravel-sitemap#196]
Hi, can you please help. Using php artisan sitemap:generate on localhost actually works great, while the same on a real web server returns nothing but:
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>

```

What's the problem here?

**Comment by freekmurze** [comment]
Duplicate of #179

**Comment by sergeevpasha** [comment]
sorry but i have no problems with robots, i dont even have robots.txt or any other restrictions. that's no help to me =(

**Comment by vanniewelt** [comment]
Why are these issues closed with no resolution at all? I have same problem.

**Comment by romansidorov** [comment]
> Why are these issues closed with no resolution at all? I have same problem.

Check option RequestOptions::ALLOW_REDIRECTS in sitemap.php and try to set it true.

**Comment by bsam2019** [comment]
This is I solved this problem.

I just made sure APP_URL in .env file was set properly. I added, for example, https://example.com/, and boom it worked
