### ISSUE TITLE
problem with genarate sitemap

### ISSUE THREAD

**Issue by soldoz** [spatie/laravel-sitemap#197]
hi
and tanks for your sitemap

my problem is how use loop like foreach to create sitemap.
start loop
->add(Url::create('/home')
        ->setLastModificationDate(Carbon::yesterday())
        ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
        ->setPriority(0.1))
end loop

tanks for help

**Comment by freekmurze** [comment]
You’ll find some examples on how to use this package in the readme.
