### ISSUE TITLE
Priority 0 is missing in sitemap.xml

### ISSUE THREAD

**Issue by emanuelmutschlechner** [spatie/laravel-sitemap#205]
If the priority is set to `0` then it won't be in the final `sitemap.xml` which defaults to a priority of `0.5` when crawled by the search engines. The reason for this is this condition in [url.blade.php](https://github.com/spatie/laravel-sitemap/blob/master/resources/views/url.blade.php#L17-L19):
```blade
@if (! empty($tag->priority))
    <priority>{{ $tag->priority }}</priority>
@endif
```

There was already a PR https://github.com/spatie/laravel-sitemap/pull/144 which clamped the priority and changed the default priority to `0.5`.  I don't think the default priority should be changed like @brendt already pointed out, some people might rely on `0.8`.

Suggestion:
- Make the default priority configurable, e.g. add it to the `config.php` with `0.8` as default value.
- Allow setting the priority to `null` in [Url.php](https://github.com/spatie/laravel-sitemap/blob/master/src/Tags/Url.php#L88). In not `null`, clamp it.
- Update the condition in `url.blade.php` to something like this:
```blade
@if (is_numeric($tag->priority) || is_numeric(config('sitemap.default_priority')))
    <priority>{{ $tag->priority ?? config('sitemap.default_priority') }}</priority>
@endif
```

@freekmurze What's do you think? Let me know if I should implement it.

**Comment by freekmurze** [comment]
> Make the default priority configurable, e.g. add it to the config.php with 0.8 as default value.
Ok, send a PR for that

> Allow setting the priority to null in Url.php. In not null, clamp it.
What is clamping?
