### ISSUE TITLE
Create sitemap for custom hostname?

### ISSUE THREAD

**Issue by iwasherefirst2** [spatie/laravel-sitemap#207]
My Laravel App works with multiple domains. Can one customize the hostname? 

From the docs I hoped this would work:

```
  $sitemap = Sitemap::create('https://example.com')

          ->add(Url::create('/home')
              ->setLastModificationDate(Carbon::create('2018', '1', '1'))
              ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
              ->setPriority(0.7))

          ->writeToFile(public_path() . '/sitemap/example.xml');
```

But in the `example.xml'` I found `https://my-def-domain.com/home` instead of `https://example.com/home`

**Comment by emanuelmutschlechner** [comment]
`Sitemap::create` does have any arguments. You can use `SitemapGenerator::create` which will then crawl your page.
```php
SitemapGenerator::create('https://example.com')
   ->getSitemap()
   ->add(Url::create('/extra-page')
        ->setLastModificationDate(Carbon::yesterday())
        ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
        ->setPriority(0.1))

    ->add(...)

    ->writeToFile($path);
```

**Comment by iwasherefirst2** [comment]
Oh.. your right, I miss read that from the docs. Is there anyway how to change the hostname.

**Comment by emanuelmutschlechner** [comment]
This package uses the Laravel [`url()`](https://laravel.com/docs/master/helpers#method-url) helper function to generate full urls.

You can force a custom root url, but be aware that depending on your use case and where you use it, it may break something:
```php
resolve('url')->forceRootUrl('http://my-sub.example.com');

Sitemap::create()...
```

**Comment by AlexMcDee** [comment]
> This package uses the Laravel [`url()`](https://laravel.com/docs/master/helpers#method-url) helper function to generate full urls.
> 
> You can force a custom root url, but be aware that depending on your use case and where you use it, it may break something:
> 
> ```
> resolve('url')->forceRootUrl('http://my-sub.example.com');
> 
> Sitemap::create()...
> ```

Thanks, work great. It helped me change the link scheme depends on param.

**Comment by MehdiAghighi** [comment]
@emanuelmutschlechner when i put this line of code top of sitemap creation:
```
resolve('url')->forceRootUrl("https://linom.ir");
```

i don't know why but it creates sitemap via `http` and not `https` !
