### ISSUE TITLE
empty sitemap

### ISSUE THREAD

**Issue by sergeevpasha** [spatie/laravel-sitemap#210]
I would like you to pay a little bit of attention to that topic. My sitemap keep generating an empty result. But I did some research and hope you can help me now.
I Used Laravel 5.7.12 with laravel-sitemap 5.2.5 and spatie/crawler 4.2.0 and it keeps generating me nothing. So I decided to downgrade and managed, that the latest version that works uses crawler version 4.0.3 and as a result sitemap 5.1.0 with downgraded laravel to 5.6.39. In this case it works as expected.
I was looking for a problem so I found
```
    protected function getCrawlObserver(): Observer
    {
        $performAfterUrlHasBeenCrawled = function (UriInterface $crawlerUrl, ResponseInterface $response = null) {
            $sitemapUrl = ($this->hasCrawled)(Url::create((string) $crawlerUrl), $response);

            if ($this->shouldStartNewSitemapFile()) {
                $this->sitemaps->push(new Sitemap);
            }

            if ($sitemapUrl) {
                $this->sitemaps->last()->add($sitemapUrl);
            }
        };

        return new Observer($performAfterUrlHasBeenCrawled);
    }
```
and if i will add for example `dd($sitemapUrl);` after  `$sitemapUrl = ($this->hasCrawled)(Url::create((string) $crawlerUrl), $response);` It won't be even executed. No idea why.
If that can help I am on Ubuntu 18.10, nginx 1.15.5, php 7.2

UPD: Did more research!
Updated to 2.5.5 and crawler 4.2.0 WITH Laravel 5.6.39 - And it works! But once update to 5.7.12 - It stops again!

**Comment by emanuelmutschlechner** [comment]
Hi can you share the code where you're using `SitemapGenerator::create`?

**Comment by emanuelmutschlechner** [comment]
If you running your laravel application locally via `php artisan serve` and the root ulr has a port in it, then `config(’app.url')` won't work as expected. Try `url('/')` instead

**Comment by sergeevpasha** [comment]
no that's not a problem. I tried full url, /, another url. It''s the same. My application is in prod on live server

**Comment by emanuelmutschlechner** [comment]
Alright thats weird. I tested it locally with Laravel 5.7.12 and had no problems with the crawler.

I used your generator code and added the two debug logs. 
```php
SitemapGenerator::create(config('app.url'))
     ->shouldCrawl(function (UriInterface $url) {
           \Illuminate\Support\Facades\Log::debug('should crawl', compact('url'));
           return true;
     })
     ->hasCrawled(function (Url $url) {
          \Illuminate\Support\Facades\Log::debug('has crawled', compact('url'));
           // ....
      });
```
![image](https://user-images.githubusercontent.com/27734375/47851024-a58d2d00-ddd7-11e8-8acd-b4e0b026eeec.png)

**Comment by sergeevpasha** [comment]
if that can help i have 0 logs in nginx log. So crawler is not even see the website

**Comment by jehadja** [comment]
Hi , thanks for this package 
![image](https://user-images.githubusercontent.com/17106547/47916840-8dd9a580-deb8-11e8-98d6-d528ffb72df6.png)
i have same problem , 
its generate empty sitemap  even on production i tried also hardcoded site name 'sitename.ru', still same problem and logs is empty too

**Comment by emanuelmutschlechner** [comment]
@jehadja What server do you use?

@sergeevpasha @jehadja Do you have a `robots.txt`? Can you share you nginx config?

**Comment by sergeevpasha** [comment]
no robots.txt
Here is my nginx.conf
server {
    listen 80;
    server_name site.ru www.site.ru;
    return 301 https://$server_name$request_uri;
}
server {
    listen 443 ssl http2;
    server_name site.ru www.site.ru;

    if ($host = 'www.site.ru') {
      return 301 https://site.ru$request_uri;
    }

    root /var/www/html/site.ru/public;

    index index.html index.htm index.php;

    charset utf-8;

    http2_push /css/styles.css;
    http2_push /js/jquery-3.3.1.min.js;
    http2_push /js/fancybox.min.js;
    http2_push /js/jquery-ui.min.js;
    http2_push /js/scripts.js;
    http2_push /fonts/Open_Sans/OpenSans-Regular.ttf;
    http2_push /fonts/Open_Sans/OpenSans-Bold.ttf;

	if ($request_method = "GET" ) {
	    rewrite ^([^.]*[^/])$ $1/ permanent;
	}

    ssl_certificate  /etc/nginx/ssl/site.ru/site.ru.crt;
    ssl_certificate_key /etc/nginx/ssl/site.ru/site.ru.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES256-SHA384;
    ssl_ecdh_curve secp384r1;

    ## OCSP Stapling
    resolver 8.8.4.4 8.8.8.8;
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /etc/nginx/ssl/site.ru/site.ru.crt;

    location / {

        try_files $uri $uri/ /index.php?$query_string;

        # Remove from everywhere index.php
        if ($request_uri ~* "^(.*/)index\.php(/?)(.*)") {
            return 301 $1$3;
        }
    }

    location ~ (login|dashboard) {

        try_files $uri $uri/ /index.php?$query_string;

        # MTSU
        allow 85.235.54.248/29;

        # DOMRU
        allow 91.230.155.104;
        allow 91.230.155.105;
        allow 91.230.155.106;
        allow 91.230.155.107;
        allow 188.234.247.183;

        # SergeevPP home IP
        allow 90.157.9.85/32;

        deny all;

        if ($request_uri ~* "^(.*/)index\.php(/?)(.*)") {
            return 301 $1$3;
        }
    }


    location ~ (wa-data|wa-apps|wa-content) {
        return 301 https://site.ru/catalog;
    }

    location = /shop/captcha.php {
        return 301 https://site.ru/catalog;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log on;
    access_log /var/log/nginx/site.ru.access.log;
    error_log  /var/log/nginx/site.ru.error.log warn;
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    sendfile off;

    client_max_body_size 100m;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors off;
        fastcgi_buffer_size 256k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        fastcgi_connect_timeout 30;
        fastcgi_send_timeout 30;
        fastcgi_read_timeout 30;
    }

    location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|woff|woff2|svg|webp)$ {
        expires 30d;
        add_header Pragma public;
        add_header Cache-Control "private";
    }

    location ~ /\.ht {
        deny all;
    }

}

**Comment by jehadja** [comment]
hi and thanks for try to help .
Robots.txt
`User-agent: *
Disallow: /*?*
Disallow: /*/*?*
Disallow: /*/*/*?*
Disallow: /*/*/*/*?*
Disallow: /*/*/*/*/*?*
Disallow: /*.php*
 
User-agent: Yandex
Disallow: /*?*
Disallow: /*/*?*
Disallow: /*/*/*?*
Disallow: /*/*/*/*?*
Disallow: /*/*/*/*/*?*
Disallow: /*.php*

User-agent: Googlebot
Disallow: /*?*
Disallow: /*/*?*
Disallow: /*/*/*?*
Disallow: /*/*/*/*?*
Disallow: /*/*/*/*/*?*
Disallow: /*.php*

User-agent: Googlebot-image
Disallow:

User-agent: StackRambler
Disallow: /*?*
Disallow: /*/*?*
Disallow: /*/*/*?*
Disallow: /*/*/*/*?*
Disallow: /*/*/*/*/*?*
Disallow: /*.php*

Host: https://site.ru
Sitemap: https://site.ru/sitemap.xml
`
Nginx 
`
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name site.ru;
    root /home/forge/site.ru/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/site.ru/434455/server.crt;
    ssl_certificate_key /etc/nginx/ssl/site.ru/434455/server.key;

    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/site.ru/server/*;

    location / {
        
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/site.ru-error.log error;

    error_page 404 /index.php;

    location ~*  \.(jpg|jpeg|png|gif|ico|css|js|webp)$ {
            expires 365d;
    }
    
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
`

**Comment by sergeevpasha** [comment]
@jehadja remove robots and try again

**Comment by freekmurze** [comment]
As this issue is probably not caused by the package, I'm going to close it.

**Comment by newklear-job** [comment]
I had same problem when my pages had <meta name="robots" content="noindex, nofollow"> tag. After commenting them everything worked fine.
