### ISSUE TITLE
Laravel 5.7 Sitemap::create() error

### ISSUE THREAD

**Issue by Dronax** [spatie/laravel-sitemap#215]
Hello. I have problem. When I try do command with this:

`Sitemap::create()
            ->add('/page1')
            ->add('/page2')
            ->add(Url::create('/page3')->setLastModificationDate(Carbon::create('2016', '1', '1')))
            ->writeToFile(public_path('sitemap.xml'));`

I get error:

> Too few arguments to function Spatie\Sitemap\Tags\Sitemap::create(), 0 passed in /Applications/MAMP/htdocs/site.com/app/Console/Commands/GenerateSitemap.php on line 35 and exactly 1 expected

How I can resolve this?

**Comment by freekmurze** [comment]
The error messages indicated that you're using the wrong class.

Be sure to use `Spatie\Sitemap\Sitemap::create()`
