### ISSUE TITLE
how to generate sub page of sitemap

### ISSUE THREAD

**Issue by richaInfowind** [spatie/laravel-sitemap#217]
Hello,
how to generate sub page of sitemap Like My url (https://www.abc.net/ab-sub/). 
so, i have multiple url in inside of this url Like 
(1: https://www.abc.net/ab-sub/a, 
2: https://www.abc.net/ab-sub/b, 
3: https://www.abc.net/ab-sub/c)

i need this 3url in sitemap and generate xml.

**Comment by freekmurze** [comment]
This behaviour isn't supported out of the box but you could achieve this with a custom crawl profile

https://github.com/spatie/laravel-sitemap#define-a-custom-crawl-profile
