### ISSUE TITLE
All pages will be crawled, except multiple page

### ISSUE THREAD

**Issue by richaInfowind** [spatie/laravel-sitemap#218]
Hello,
 Its not working. Please help me
SitemapGenerator::create('https://example.com')
   ->shouldCrawl(function (UriInterface $url) {

       if((strpos($url->getPath(), '/contact') === false) && (strpos($url->getPath(), '/what-is-acn') === false) {
	    			return;
	    		}
   })
   ->writeToFile($sitemapPath);

**Comment by MitchellBouwman** [comment]
I think it should be something like

> if((strpos($url->getPath(), '/contact')) || strpos($url->getPath(), '/what-is-acn') === false)) {
> return;
> }

**Comment by Akilez** [comment]
```php
SitemapGenerator::create('https://example.com')
   ->shouldCrawl(function (UriInterface $url) {
      return 
        strpos($url->getPath(), '/contact') === false |
        strpos($url->getPath(), '/what-is-acn') === false
}
```

**Comment by atymic** [comment]
@richaInfowind 
Did the code above solve your issue?

**Comment by Areg1189** [comment]
Please help me, too, does not open the page

SitemapGenerator::create('https://example.com')
        ->shouldCrawl(function (Psr\Http\Message\UriInterface $url) {
           return ! strpos($url->getPath(), '/admin/')  ||
                ! strpos($url->getPath(), '/public/')  ||
                ! strpos($url->getPath(), '/profile/')  ||
                ! strpos($url->getPath(), '/c-owner/')  ||
                ! strpos($url->getPath(), '/currency/')  ||
                ! strpos($url->getPath(), '/auth/')  ||
                ! strpos($url->getPath(), '/login')  ||
                ! strpos($url->getPath(), '/register')  ||
                ! strpos($url->getPath(), '/password/')  ||
                 ->writeToFile($sitemapPath);

        })
        ->writeToFile('sitemap.xml');

**Comment by jonodonovan** [comment]
What's the correct way to do this? I'll update submit a PR for the docs.
