### ISSUE TITLE
Cant set empty values to url tags

### ISSUE THREAD

**Issue by projct1** [spatie/laravel-sitemap#220]
Hello!
I dont need `priority`, `lastmod`, `frequency` etc tags. But and i cant set it as `null` or empty!
```php
$url = Url::create($url)
    ->setChangeFrequency(null)
    ->setLastModificationDate(null)
    ->setPriority(null);

Sitemap::create()->add($url);
```
Because of php type-hints i got error of course: `Argument 1 passed to Spatie\Sitemap\Tags\Url::setChangeFrequency() must be of the type string, null given`

What the limitations? 🤔

**Comment by freekmurze** [comment]
I think you can just leave off the `set` methods.

```
$url = Url::create($url);
```

**Comment by projct1** [comment]
@freekmurze Yas, but if i just write `Url::create($url);`, url will be write with unnecessary for me tags, because constructor uses default values and it is uncontrollable :(
```php
    public function __construct(string $url)
    {
        $this->url = $url;
        $this->lastModificationDate = Carbon::now(); //I cant set this to empty
        $this->changeFrequency = static::CHANGE_FREQUENCY_DAILY; //I cant set this to empty
    }
```

**Comment by freekmurze** [comment]
I'd accept a fully tested and documented PR that adds this to the package.

**Comment by Dronax** [comment]
Please do set lastModificationDate, changeFrequency is null. Thanks.
