### ISSUE TITLE
error while generating

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-sitemap#221]
I'm trying to run the command by PUTTY (ssh) on server and i get this error:

```bash
 Spatie\Sitemap\Sitemap::writeToFile("/hom.../............/..........ine/public/sitemap.xml")
/hom.../............./.........ine/vendor/spatie/laravel-sitemap/src/SitemapGenerator.php:158
```

![545](https://user-images.githubusercontent.com/8672823/50052252-be695c00-0153-11e9-9568-02555fd9b4f4.png)

Any idea?

**Comment by freekmurze** [comment]
I can't see the actual error message, so I can't help you with this.
