### ISSUE TITLE
Some pages (seems random) not being indexed; cannot figure out why

### ISSUE THREAD

**Issue by nexxai** [spatie/laravel-sitemap#222]
I run the sitemap generator daily using the scheduler however I've noticed that it is consistently not adding certain URLs, but I can't figure out what's different about them than other similar (and dissimilar) models that *do* end up being added.

I don't believe it's a depth issue as I don't have a limit set, nor are at least some of these missing objects very deep.  

For example, say we have Model:: and models $ModelA, $ModelB, $ModelC, $ModelD, $ModelE.  To see that each exist and to find the link for their model.show view+route, the spider would simply need to follow this path: link from navbar -> models.index.  Except when I open the sitemap, $ModelA, $ModelB, $ModelD, and $ModelE is in sitemap.xml yet $ModelC is not. 

That's a very simple example, as my site is vaguely similar to a Wiki, so there are many MANY links being indexed (the final size of sitemap ends up being ~4.3MB right now) but it seems like there's little rhyme or reason as to why $ModelC wasn't indexed.

Given the quality of your packages, I'm assuming it's a user problem and not code-based, but I don't know where else I should look, like if there's logging I can investigate or something.

Thanks!

**Comment by nexxai** [comment]
@freekmurze Any idea?  I'd be happy to provide whatever you need to help figure out what's going on.

**Comment by Livijn** [comment]
I am experiencing the same issue. In my footer, I have a link to an index page that displays a paginated listing of 157 items. Only 68 of these show up in the *sitemap.xml*. I am also noticing some other pages missing.

**Comment by Akilez** [comment]
Things to try: 
`php artisan route:clear`
`php artisan route:cache`

Then re-run the sitemap. Compare against your route file **and** against `php artisan route:list`
If/when all fails, send me a copy of the route file, list and the result .xml.  I'd happily give it a look.

**Comment by nexxai** [comment]
I ended up just giving up.  The sitemap generation was taking more than 8 hours to run (due to it being very wiki-ish with TONS of links to spider) and ended up using Laravelium's sitemap generator (https://gitlab.com/Laravelium/Sitemap) which brought the generation time down to a couple seconds, and all I had to do was define the models and iterate over them:

```
➜  site git:(develop) time php artisan sitemap:generate
Sitemaps generated
php artisan sitemap:generate  1.94s user 0.20s system 91% cpu 2.332 total
➜  site git:(develop) 
```

I will leave this issue open for those who are still having this problem but I will simply unsubscribe from notifications.

**Comment by Livijn** [comment]
I also went with creating all links manually. You can do that with this package as well: https://github.com/spatie/laravel-sitemap#manually-adding-links
