### ISSUE TITLE
not working in laravel 5.7

### ISSUE THREAD

**Issue by Sarfroz** [spatie/laravel-sitemap#226]
everything is fine only the paths are not getting printed. i am getting only this

`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>`

**Comment by freekmurze** [comment]
The tests indicate that this package is working as expected.

Please make sure that you pass the correct URL to `SitemapGenerator::create()` 

Try to make a request with curl to that url to make sure that the url is responding as expected.
