### ISSUE TITLE
Homepage was indexed twice with http and https protocol separately

### ISSUE THREAD

**Issue by UXandre** [spatie/laravel-sitemap#227]
Hi there,

My Sitemap generator works well except one thing - that home was listed twice with http and https protocol separately. Tried to clear all the caches and still works like this. Other pages work just fine with only https protocol.

I can't even exclude this one as temp solution because there is no 'segment' for it. Can anyone help?

Thanks a million in advance.

**Comment by atymic** [comment]
Strange, can you provide a link to the site you are crawling?
Do you have redirects from `http` to `https` setup?

**Comment by UXandre** [comment]
Thanks for replying @atymic 

Yes sure. The link is to the website is: [https://favourup.com](https://favourup.com)

And yes again. The http is redirected to https with a 301 redirection. Thanks!
