### ISSUE TITLE
Crawling two versions of the website

### ISSUE THREAD

**Issue by sofiane-soufi** [spatie/laravel-sitemap#229]
Hi,

I'm trying to generate a sitemap that contains two versions of the website. We have some products on our website that we display only to US customers and some only to CA customers. I'd like to combine them both. Is there anyway to do so?

Regards,
Sofiane Soufi,
CTO of Trunkshop.

**Comment by atymic** [comment]
How does localisation work on your site?
Are the sites on different subdomains or different paths, etc? How do you configure which site to visit?
