### ISSUE TITLE
Missing XML Header xmlns:xhtml="http://www.w3.org/1999/xhtml

### ISSUE THREAD

**Issue by raicem** [spatie/laravel-sitemap#231]
It looks to me that this header (`xmlns:xhtml="http://www.w3.org/1999/xhtml`) is removed with the PR #228 . Are we sure about removing it? 

Google webmaster tools, Firefox and [XML Sitemap validator](https://www.xml-sitemaps.com/validate-xml-sitemap.html) mentioned above, all fail when I add alternate links (multilanguage) to the sitemaps. No problems arise when I don't use the alternate links tho.

I don't know much about XML but it looks to me like that one can be added back. Only reference I found is [this](https://stackoverflow.com/questions/5838343/what-does-html-xmlns-http-www-w3-org-1999-xhtml-do) SO answer.

I reverted back to the 5.2.7 version to avoid this issue.

**Comment by davidbonting** [comment]
Hi Raicem,

I was watching this repository closely to check if no one would run into problems with such "big change" (changing the headers).

I'm wondering if you have the same problem as I had that if you would add "priority" with a , notation in your version of laravel-sitemap, it would fail.

So check this generated file:
`<urlset
	xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xhtml="http://www.w3.org/1999/xhtml">

	<url>
		<loc>***</loc>
		<lastmod>2019-02-10T01:00:02+00:00</lastmod>
		<changefreq>daily</changefreq>
		<priority>0,8</priority>
	</url>
	<url>
		<loc>***</loc>
		<lastmod>2019-02-10T01:00:04+00:00</lastmod>
		<changefreq>daily</changefreq>
		<priority>0,8</priority>
		<xhtml:link 
               rel="alternate"
               hreflang="de"
               href="***"/>
	</url>

</urlset>`

 If I use it in Google webmasters I do get an error:
![example1](https://user-images.githubusercontent.com/6029739/52532995-7cacfa00-2d2d-11e9-8db3-cb66b781764b.PNG)

But I've now tested it some more, and it seems like keeping only the number_format(*) adjustment of [that pull request](https://github.com/spatie/laravel-sitemap/pull/228) is enough to get it right. It's a pretty safe adjustment compared to the header change.

So let's revert my changes :)

#232

**Comment by raicem** [comment]
Not sure if I can comment about the priority dot/comma notation issue. It was not a issue for me. 

My 5.2.7 generated sitemap.xml resides [here](https://ancientcitiesturkey.com/sitemap.xml) if you would like to inspect. The code that generates the sitemap is [here](https://github.com/raicem/ancient-cities-turkey/blob/master/app/Console/Commands/GenerateSitemap.php).

Thanks for taking interest and the pull request!

**Comment by davidbonting** [comment]
Seems like you do get a . standard. I have no idea why I'm getting a , with a fresh Linux (vps), Windows (Wamp) or Linux (Docker).

I'm waiting on [freekmurze](/freekmurze) to accept my changes, I'll keep you posted.

**Comment by davidbonting** [comment]
@raicem my latest pull request was accepted. So it should solve your issues.

@freekmurze Thank you, and I'm sorry for the extra work... :(

**Comment by raicem** [comment]
Thank you very, very much @davidbonting. I think we can close the issue now.
