### ISSUE TITLE
How to change sitemap namespace ?

### ISSUE THREAD

**Issue by hsntngr** [spatie/laravel-sitemap#235]
As the title, how can I add new xhtml namespace to sitemap ? Because I'm generating multilingual sitemap but it's crashing without `http://www.w3.org/TR/xhtml11/xhtml11_schema.html` namespace ? is package support to expand xhtml namespace ?

**Comment by raicem** [comment]
Hi @hsntngr , I have run into a similar issue myself with the version 5.2.8 (Issue #231). Luckily @davidbonting quickly issued a fix. If you are experiencing a similar error, it may resolve once you update laravel-sitemap to 5.2.9 version.

**Comment by hsntngr** [comment]
thanks for your reply @raicem, I'm currently using 5.2.7 and the namespace you mentioned already exists. In my situation sitemap validators says fine but when I opened sitemap on browsers, its crashing and displaying sitemap as plain texts. Without `http://www.w3.org/TR/xhtml11/xhtml11_schema.html` namespace, its not work properly. So even if it passes the sitemap tests, it scares me what if google still takes that as a problem..
