### ISSUE TITLE
Outcome is not completely formatted

### ISSUE THREAD

**Issue by Amsterdamys** [spatie/laravel-sitemap#237]
That's how my generated sitemap looks like now:
![screenshot_7](https://user-images.githubusercontent.com/3232259/52859372-92f7f300-313d-11e9-8623-6310a640aa65.png)

`<loc>` tag is not tabbed, and there is an extra empty line after opening `<url>` tag 

I assume it should look like:

![screenshot_9](https://user-images.githubusercontent.com/3232259/52859492-ee29e580-313d-11e9-8d20-6503645a099b.png)

**Comment by freekmurze** [comment]
Feel free to PR a fix!
