### ISSUE TITLE
How to output special characters?

### ISSUE THREAD

**Issue by alldeads** [spatie/laravel-sitemap#244]
I want to output the specific character, but I ended up getting the entity value.

`Sitemap::create()->add("/&&")`

The output file would look like:

`<loc>https://example.com/&amp;&amp;</loc>`

Is there any way that the output will not convert into HTML entities?

_Originally posted by @alldeads in https://github.com/spatie/laravel-sitemap/issues/243#issuecomment-469075329_

**Comment by Livijn** [comment]
That is the correct output. [Learn more here.](https://webmasters.stackexchange.com/questions/4175/amp-in-sitemap-links-are-they-correct)

**Comment by atymic** [comment]
@alldeads 
As per the above answer, are you able to close the issue?
