### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by nexthis** [spatie/laravel-sitemap#246]
in Laravel 5.7.28
`Problem 1
    - Installation request for spatie/laravel-sitemap ^5.3 -> satisfiable by spatie/laravel-sitemap[5.3.0].    - Conclusion: remove laravel/framework v5.7.28
    - Conclusion: don't install laravel/framework v5.7.28
    - spatie/laravel-sitemap 5.3.0 requires illuminate/support ~5.8.0 -> satisfiable by illuminate/support[5.8.x-dev, v5.8.0, v5.8.2, v5.8.3, v5.8.4].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.7.28
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.7.28
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].`

**Comment by Barrykilby** [comment]
I presume this is due adding compatibility for the soon to be released Laravel 5.8, adding: `    "spatie/laravel-sitemap": "5.2.11",` to composer.json works for me with the same issue for now.

Barry
