### ISSUE TITLE
Generates empty sitemap while using https

### ISSUE THREAD

**Issue by parthshah000** [spatie/laravel-sitemap#247]
While using `APP_URL:http://127.0.0.1:8000` it generates the complete sitemap.
While using `APP_URL:https://domain.test` it generates this code.

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>
```

**Comment by SergiBaucells** [comment]
Hello @parthshah000 ,

The package doesn't work with valet secure, because it doesn't provide a valid public https. Try it with valet share.

**Comment by Livijn** [comment]
To use it with Laravel Valet you can set `RequestOptions::VERIFY => false` in the config file `sitemap.php`. 

if you haven't already published the config file, you can [read about it here](https://github.com/spatie/laravel-sitemap#configuration).

**Comment by connor11528** [comment]
I am getting an empty sitemap for my production site that's using https. Is this the intended behavior?

```
    public function handle()
    {
        // modify this to your own needs
        SitemapGenerator::create('https://employbl.com')
            ->getSitemap()
            ->writeToFile(public_path('sitemap.xml'));
    }
```
Output is only 1 URL despite my site having many URLs.. https://www.employbl.com/sitemap.xml

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
<url>
<loc>https://employbl.com/</loc>
<lastmod>2021-02-05T21:03:23+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.8</priority>
</url>
</urlset>
```
