### ISSUE TITLE
Laravel error wile generating sitemap

### ISSUE THREAD

**Issue by Disenosos** [spatie/laravel-sitemap#249]
In my local works perfect, but when i use in my external hosting i get the error

**file_put_contents(sitemap.xml): failed to open stream: Permission denied**

I need to change something??

**Comment by m-a-k-o** [comment]
@Disenosos I guess, permission are missing for folder when you want to store your sitemap.

**Comment by atymic** [comment]
You may want to consider changing the file permissions on your hosting for that file so that larvael can write it. It's a bit hard to help without details of your hosting  environment.

**Comment by Disenosos** [comment]
I have digitalocean with LAMP and cloudflare free version for https. What permissions need for the folder??

**Comment by atymic** [comment]
@Disenosos 	
Can you run `ls -li | grep "public"` in your laravel installation folder?
If you are running lamp, it probably needs to be owned and writeable by `www-data`

**Comment by Disenosos** [comment]
i received these `1058580 drwxr-xr-x  6 root www-data   4096 Apr 20 19:13 public`

**Comment by atymic** [comment]
Ok, that seems correct.
Can you do `ls -li public/` and check the permissions on `sitemap.xml`?

**Comment by Disenosos** [comment]
The file sitemap.xml does not appear

**Comment by atymic** [comment]
Ok, it seems like `root` user owns that folder which would be the issue I think.

```
sudo chown -R www-data:www-data /path/to/laravel
chmod -R 775 /path/to/laravel/public
```
should set the owner to `www-data` user and make the public folder writable, then try creating the sitemap again.

(obviously, i take no responsibly for any issues caused by above, do your own research before running commands)

**Comment by Disenosos** [comment]
i can change the path of sitemap?? and i run that commands in that new folder

**Comment by atymic** [comment]
Another way would be to change it to save the sitemap in the laravel storage folder, and then serve the file using a laravel route.
