### ISSUE TITLE
Pagination in Sitemap

### ISSUE THREAD

**Issue by tisuchi** [spatie/laravel-sitemap#251]
Hello 

First of it's really a helpful package. I am wondering is there any way to do paginate in Sitemap so that all f my post will be added in the sitemap?

Currently here is my sitemap url https://sclrship.com/sitemap.xml that doesn't cover all the url. I am expecting is there any way to do paginate the sitemap so that it will be like this -

https://sclrship.com/sitemap.xml?page=2
https://sclrship.com/sitemap.xml?page=3
https://sclrship.com/sitemap.xml?page=4

And so on..

**Comment by freekmurze** [comment]
There is no support for pagination.
