### ISSUE TITLE
Minimum Crawl Depth - Products not being listed

### ISSUE THREAD

**Issue by kinger251285** [spatie/laravel-sitemap#254]
I have the sitemap running and producing as it should.

However not all my links are being crawled

Index - crawled
Categories (Sports) - crawled
Sub-Categories (Countries) - crawled
Sub-Sub Category (Regions) - Not Crawled
Products (Package listings) - not crawled

So a link example would be - mydomain/Sport/Country/Region

But i need to display the links on the region page like the following - mydomain/Sport/Country/Region/SportsVenue 

And then the subsequent links that are on the SportsVenues pages.

I hope this makes sense

**Comment by freekmurze** [comment]
I'm sorry, I don't have time to dive into specify project, and I'm not sure I understand your issue. Could you PR a failing test for me to fix?
