### ISSUE TITLE
Possibly get priority and changefreq via meta tags during crawl?

### ISSUE THREAD

**Issue by Riaan-ZA** [spatie/laravel-sitemap#255]
Hi, I'm storing priority and changefreq values for my pages in the database in order to give the user full control over this. 

Is there any way of setting the crawler to get these values during crawl (possibly by setting them in the template as meta tags), rather than doing it using the hasCrawled, which could get pretty long and complicated.

**Comment by freekmurze** [comment]
Currenlty there is no way to do this, but I'd welcome a PR with tests, that adds this to the package.
