### ISSUE TITLE
Setting a more precise priority

### ISSUE THREAD

**Issue by vmeijer** [spatie/laravel-sitemap#256]
Hello, I have a question about setting a more precise priority.

It does not seem possible to create an entry for the sitemap with two decimals.

If I use the following, the result in my sitemap is `0.6` instead of `0.61`:
```php
use Spatie\Sitemap\SitemapGenerator;
use Spatie\Sitemap\Tags\Url;

SitemapGenerator::create($url)
    ->getSitemap()
        ->add(Url::create('the url')
            ->setChangeFrequency(Url::CHANGE_FREQUENCY_WEEKLY)
            ->setPriority(0.61));
    ->writeToFile(public_path('sitemap.xml'));
```

When I set the priority at `0.65` the result in my sitemap is `0.7` instead of `0.65`.

I checked the file `spatie/laravel-sitemap/src/Tags/Url.php` where the method `setPriority` is present. I assumed the second decimal was removed/changed here, but I do not see an additional `floor()` or `ceil()` in the `setPriority`-method.

Where are the decimals rounded and how can I override this removal of extra decimals?

**Comment by vdbelt** [comment]
The rounding is done in the url.blade.php view. 

By publishing the views, you could easily override this behaviour.

Note that Google [doesn't really care](https://support.google.com/webmasters/answer/183668?hl=en) about the priority tag.
