### ISSUE TITLE
[Suggestion] Adding unique to $this->tags would be good to prevent duplicate URLs.

### ISSUE THREAD

**Issue by technoknol** [spatie/laravel-sitemap#257]
I'm generating sitemap with `$sitemap = SitemapGenerator::create(env('APP_URL'))->getSitemap()` and because home page doesn't include all the links, I'm adding it later like 
```
$products = Products::select(['id', 'url_hash'])->get();
        foreach(products as $url) {
            $sitemap
                ->add(Url::create(route('show', ['md5' => $url->url_hash])));
        }
```

So this `$products` already have those links which all are in homepage. This is resulting into duplicate links in `sitemap.xml`

### Suggestion 
Adding a unique filter along with `sort` (which is already there) would solve this issue.

**Comment by freekmurze** [comment]
Feel free to submit a PR with tests for this.
