### ISSUE TITLE
Manually create a sitemap index with sub-sequent sitemaps

### ISSUE THREAD

**Issue by Zontir** [spatie/laravel-sitemap#258]
I would like to use the maxTagsPerSitemap function but manually creating the sitemap for example:

```
Sitemap::create()
   ->add('/page1')
   ->add(Url::create('/page3')->setLastModificationDate(Carbon::create('2016', '1', '1')))
   ->maxTagsPerSitemap(1000)
   ->writeToFile($sitemapPath);
```
It would be really useful because I don't want to scan all the urls on my site so I can generate them much faster myself.

**Comment by freekmurze** [comment]
When manually creating sitemaps, you are responsible for keep tracking how many items you added. I'd probably merge a PR that adds a `count` method to `Sitemap`. That function could help you decided whether you want to add more items or not.

**Comment by Goahnary** [comment]
Is there a way for the package to handle creating a sitemap index with sub-sequent sitemaps while adding links manually? We have over 60,000 products that I am making a sitemap for manually and I need the package to be able to handle this as it scales.

Or maybe you can suggest a way I work around this outside of manually writing the XML for the index?

**Comment by Goahnary** [comment]
Now that I am looking more closely at creating a Sitemap Index I believe the solution for this would be:
- Create the index
- Keep track of how many you are creating 
- Every time you create a sitemap with your maximum number of links, add that sitemap to the sitemap index and continue processing links. 

This isn't outlined in the documentation so I think it would be good to leave an example on this issue for future developers to see.

Code Example:

```
$siteMapIndex = SitemapIndex::create();
$siteMap = Sitemap::create(config('app.url'))

while ($LinksLeft > 0)
    while($linksCreated < 20000) {
        $siteMap->add($link);
        $linksCreated++;
    }
    $siteMapIndex->add($sitemap);
}
```

I am attempting to implement this. I will come back and edit this answer if I am wrong.

**Comment by royduin** [comment]
Another (cleaner) approach:

```php
$sitemapIndex = SitemapIndex::create();

$productChunks = Product::all()->chunk(50000);
foreach ($productChunks as $chunk => $products) {
    $sitemapName = 'products_sitemap_'.($chunk + 1).'.xml';
    $sitemap = Sitemap::create();

    foreach ($products as $product) {
        $sitemap->add(Url::create($product->slug)
                ->setLastModificationDate($product->updated_at));
    }

    $sitemap->writeToFile(public_path($sitemapName));
    $sitemapIndex->add($sitemapName);
}

$sitemapIndex->writeToFile(public_path('sitemap.xml'));
```
