### ISSUE TITLE
Looping through an array

### ISSUE THREAD

**Issue by ashpuk** [spatie/laravel-sitemap#259]
HI,

I have already seen this issue: https://github.com/spatie/laravel-sitemap/issues/198

I have the same problem, however the solution link that they provided does not work.

Are you able to advise if there is any recommended method for looping through an array to generate the sitemap?

Thanks

**Comment by riasvdv** [comment]
The url is not broken, it links to https://freek.dev/557-automatically-generate-a-sitemap-in-laravel now, you might have some mapping on your system that still resolves `.dev` domains wrong.

As for your question, the relevant part of the article should be this:

```php
use Spatie\Sitemap\Sitemap;
use Spatie\Tags\Url;

$sitemap = Sitemap::create()
    ->add(Url::create('/home'))
    ->add(Url::create('/contact'));

NewsItem::all()->each(function (NewsItem $newsItem) use ($sitemap) {
    $sitemap->add(Url::create("/news/{$newsItem->slug}"));
});

Projects::all()->each(function (Project $project) use ($sitemap) {
    $sitemap->add(Url::create("/project/{$project->slug}"));
});

$sitemap->writeToFile(public_path('sitemap.xml'));
```

**Comment by PHPAdam** [comment]
This should be in the documentation.

**Comment by riasvdv** [comment]
Feel free to send a PR with the addition to the Readme!
