### ISSUE TITLE
Add use Spatie\Sitemap\Sitemap; to Readme.md section

### ISSUE THREAD

**Issue by n3omaster** [spatie/laravel-sitemap#260]
When explaining the Manually creating a sitemap 
https://github.com/spatie/laravel-sitemap#manually-creating-a-sitemap

Please add `use Spatie\Sitemap\Sitemap;` below `use Carbon\Carbon;`

that could bring less error for newbies 👍

**Comment by freekmurze** [comment]
Feel free to PR improvements to the readme.
