### ISSUE TITLE
Not taking in account the 301 ad readme error

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [spatie/laravel-sitemap#263]
in both case `RequestOptions::ALLOW_REDIRECTS => false` and `RequestOptions::ALLOW_REDIRECTS => true`, it treat https://asd.asd/asd as a different page to https://asd.asd/asd/ .. by using `hasCrawled()` and checking the last character (if equals to /) i've solved the problem, but i was hoping there was a more elegant way to do that
also, in the readme, inside the hasCrawled's demo the method to get the path is `path()` and not `getPath` (if we use Spatie\Sitemap\Tags\Url instead of laravel Url class)

**Comment by atymic** [comment]
If i'm reading this right, the issue is that the package is treating urls with a trailing slash differently to those without?

**Comment by AlbertoSinigaglia** [comment]
Yes, but apparently was a Laravel cached config that cause this problem.
Can you check the other point (about getPath() and path())?
