### ISSUE TITLE
shouldCrawl does not close pages

### ISSUE THREAD

**Issue by Areg1189** [spatie/laravel-sitemap#264]
These pages that should not be in the sitemap are still present

SitemapGenerator::create('https://site.com/')
        ->shouldCrawl(function (Psr\Http\Message\UriInterface $url) {
           return ! strpos($url->getPath(), '/admin/')  ||
                ! strpos($url->getPath(), '/public/')  ||
                ! strpos($url->getPath(), '/profile/')  ||
                ! strpos($url->getPath(), '/c-owner/')  ||
                ! strpos($url->getPath(), '/currency/')  ||
                ! strpos($url->getPath(), '/auth/')  ||
                ! strpos($url->getPath(), '/login')  ||
                ! strpos($url->getPath(), '/register')  ||
                ! strpos($url->getPath(), '/password/')  ||
                ! strpos($url->getPath(), '/posts?slug')  ;
        })
        ->writeToFile('sitemap.xml');

**Comment by AlbertoSinigaglia** [comment]
shouldCrawl will crawl that folder if the function returns true... if the path is like '/public/slug'
`strpos('/public/slug', '/public/')` will return 0, so `! strpos('/public/slug', '/public/')` will be 1-> true, and so it will crawl that page... just take out all of the '!'

**Comment by brendt** [comment]
I believe @AlbertoSinigaglia answer is sufficient for you to understand why your example is wrong?
