### ISSUE TITLE
Request upgrade to support Laravel 6.0

### ISSUE THREAD

**Issue by quangvision** [spatie/laravel-sitemap#265]
Hello
Please upgrade this package to support latest version of Laravel 6.0.
   Thanks :)

**Comment by rajurajpurohit** [comment]
Facing problem with Laravel 6. Please upgrade.

**Comment by Nisthar** [comment]
👍 pls upgrade. I am getting empty sitemap.xml files.

**Comment by Nisthar** [comment]
ok, i think its working for me now

**Comment by ravenshill** [comment]
I am also getting a near empty xml file.  using laravel 6.xx.  No errors are being indicated.  There is definitely no crawling of the site.  

sitemap.xml is below
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>
