### ISSUE TITLE
I'm using Laravel 5.8 whats happen with this package?

### ISSUE THREAD

**Issue by soulcodex** [spatie/laravel-sitemap#266]
I am trying to do composer require for this package and laravel show a error message requiring been a downgrade to 5.7 or a upgrade to 6.0. Whats happen with the 5.8. Please unlock this version thank you

**Comment by freekmurze** [comment]
Could you try installing it in a fresh Laravel 6 project?

**Comment by soulcodex** [comment]
No, because i have a developed project since 4 months ago and i really dont know if the new Illuminate\support 6.0 can create collisions in my project, maybe Taylor deleted helpers or another functions. yet i not readed the changelog for the new laravel

**Comment by freekmurze** [comment]
The tests of this package indicate that it should be working fine. I was able to install it into Laravel 5.8 and Laravel 6.0. If you are working in and older version of the framework please use and older version of the package.
