### ISSUE TITLE
Is this your package works in Laravel 5.3?

### ISSUE THREAD

**Issue by cleargoal** [spatie/laravel-sitemap#269]
Hello!
I just installed your package.
Thank you for this work!
I added the Service Provider into config/app.php.
I created the Command - copy/paste your code example, and added this command to app/Console/Kernel.php. All of it works fine - file 'sitemap.xml' created but contains just this:

[https://pastebin.com/JwwRSfp6](url)
(i place it to pastebin because here the part of file content become hidden)

No one page URL I see in it.
I have read all documentation here at github and not see - 
**what else can I do to fill sitemap.xml file with data about my site?**

Note: I did these all actions at my local copy but it has many links and pages.

**Comment by freekmurze** [comment]
Probably your webserver is giving the crawler a response that you don't expect and that doesn't contain any links.

Could you try performing a curl request and see what the response is? Make sure you use the exact same URL as you specified in the package (www, non-www can make a difference, adding a trailing slash may also yield different results).

**Comment by cleargoal** [comment]
Thanks for your response!

the URL that I tried to treat is just 'http://localhost'
that taken from 
APP_URL=http://localhost

May it be cause of to confuse the crowler?

**Comment by freekmurze** [comment]
That could be the case yeah, set it to a url that works in your browser too.

**Comment by cleargoal** [comment]
Thank you!
Finally, I try start command at real site and it's generated everything cool!
Thanks for  your package!
One more question, 
When my site will contain very many pages, will sitemap.xml contain all of them and be very thik?
