### ISSUE TITLE
some improvements.

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-sitemap#27]
- plz add some info regarding the currently supported version of laravel as not everyone is on v5.3 yet.

- it would be really helpful if the console cmnd was added by default because mostly users will be using this option instead of creating sitemap manually.

- maybe it would be also good if u add a default path to the config file so the user can simply use `SitemapGenerator::create(config('app.url'))->writeToFile();`

- `config('app.url')` is wrong because `APP_URL=http://localhost` which will result in empty sitemap.xml, so again having this as an option in the config file would be better.

**Comment by freekmurze** [comment]
In `composer.json` you can see that L5.3 is required. Composer won't let you install the package in older Laravel version.

To keep the package very simple I'm not going to add the command into the package. It's very easy to setup. Just copy paste the code from the readme and edit it to fit your own needs.
