### ISSUE TITLE
Error while generating - Unknown column

### ISSUE THREAD

**Issue by MitchellBouwman** [spatie/laravel-sitemap#271]
Hi,

I got this error while generating. It was working before. Where does this come from?

> SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select * from `editor_categories` where (`` = 1 and `navigation` = 1 and `parent` = 0) order by `order` asc)

**Comment by freekmurze** [comment]
Our package does not use a db. Your error is not coming from this package.
