### ISSUE TITLE
Help with LastModificationDate

### ISSUE THREAD

**Issue by henrymainforum** [spatie/laravel-sitemap#272]
I have generated my sitemap and i have set a cronjob for it, but i set the frequency to be daily because i update my site regularly.

But i noticed that the lastmodficationdate does not change which also affects the google search console last read date.

How can i change the lastmodificationdate to the last time i update each pages/posts of the website?

Here is the link: https://naijaswift.com/sitemap.xml

**Comment by freekmurze** [comment]
The package uses the `updated_at` property on your models.
