### ISSUE TITLE
Google Analytics picking up sitemap generator as person

### ISSUE THREAD

**Issue by scheMeZa** [spatie/laravel-sitemap#274]
Hello,

I have an odd situation where the sitemap generator goes through my site to create the sitemap, but then google analytics sees the robot as a human - this makes my google analytics statistics obsolete and makes my business look 100x bigger than it is 😄 

Any ideas on how I can fix this problem but still build good sitemaps?

I'm using the load javascript option to load my Vue components and I think this may be the culprit...

**Comment by sandervankasteel** [comment]
You might be able to do something by setting a custom User-Agent in spatie/crawler package (more info: https://github.com/spatie/crawler#using-a-custom-user-agent) and filtering your results inside Google Analytics by filtering out your custom user-agent 

Disclaimer; I'm not a Google Analytics expert, so I don't even know if it's possible or how... 🤷

**Comment by scheMeZa** [comment]
Thank you for your suggestion :) Will see if I can filter out based on user agents
