### ISSUE TITLE
Why did I get an error

### ISSUE THREAD

**Issue by konderson** [spatie/laravel-sitemap#278]
Symfony\Component\Debug\Exception\FatalThrowableError
Argument 1 passed to Spatie\Crawler\Crawler::create() must be of the type array, null given, called in /home/host1792843/xn--d1amkaejqfkvr9a.xn--p1ai/htdocs/www/vendor/spatie/laravel-sitemap/src/SitemapServiceProvider.php on line 25

**Comment by axtg** [comment]
Clear your cache and config (+ rerun any caching commands).
