### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ctf0** [spatie/laravel-sitemap#28]
using Lara v5.2

- error
`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 1 passed to App\Console\Commands\GenerateSitemap::App\Console\Commands\{closure}() must be an instance of Spatie\Crawler\Url, instance of Spatie\Sitemap\Tags\Url given,
  called in /www/sitename.com/vendor/spatie/laravel-sitemap/src/SitemapGenerator.php
   on line 89
`

- console handle()
```php
SitemapGenerator::create('https://lilahmagazines.com')
->hasCrawled(function (Url $url) {
        if ($url->segment(1) === 'sharer' || $url->segment(1) === 'image') {
           return;
        }
        return $url;
    })
->writeToFile(public_path('sitemap.xml'));
```

**Comment by freekmurze** [comment]
You need Laravel 5.3 to use this package. Normally composer.json should
have stopped you from installing it.





Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by freekmurze** [comment]
You need Laravel 5.3 to use this package. Normally composer.json should have stopped you from installing it.

**Comment by ctf0** [comment]
yes but there is an older version that works with v5.2 or was it for testing purposes ?

**Comment by freekmurze** [comment]
Yea, there's a version `0.0.1` that was for testing purposes only. I'll remove the version from packagist.
