### ISSUE TITLE
Write sitemap to storage disk instead of absolute path

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-sitemap#282]
It would make things a lot easier if it would be possible to write sitemaps to a storage disk + filepath instead of a single absolute path. The most common would be the `public` storage I think.

**Comment by freekmurze** [comment]
I'll revisit this issue when creating a new major version of the package.

**Comment by Gummibeer** [comment]
I think it wouldn't be breaking because it would need a new method and nothing more.

**Comment by freekmurze** [comment]
Feel free to PR this!
