### ISSUE TITLE
sitemap for arabic slugs not working

### ISSUE THREAD

**Issue by rebarhama** [spatie/laravel-sitemap#293]
sitemap generator not working very well with Arabic characters in the URL slug.
![site map](https://user-images.githubusercontent.com/15612061/73590286-d6d03d80-44f1-11ea-8cf9-7ddce4b865c6.PNG)

I think file encoding of XML file should be UTF-8 not ANSI any option?

**Comment by samehdoush** [comment]
I think it works well and to make sure of this copy the link and put it on the browser Arabic language will be with this coding to work and search engines will read it well
