### ISSUE TITLE
Priority by nesting level

### ISSUE THREAD

**Issue by spekulatius** [spatie/laravel-sitemap#294]
Hello @freekmurze 

have you considered setting the priority by the nesting level? I think this would reflect a more natural distribution of the priorities. Looking forward to have what your thoughts are.

Peter

**Comment by freekmurze** [comment]
I think sitemaps are mainly meant to be consumed by computers, no humans, so I don't think the order matters too much.

**Comment by spekulatius** [comment]
Yeah, agreed it's for machines. I assume it's somewhat used for defining priorities in the following processes (within the Google algo). But it's alright, no need to go into depth...
