### ISSUE TITLE
duplicated app url genarated in sitemap

### ISSUE THREAD

**Issue by SurfJunky** [spatie/laravel-sitemap#296]
i have a problem when i generate sitemap, 
its indexing the app url with and w/o slash

like in picture below
![Capture](https://user-images.githubusercontent.com/58202085/75623435-99270900-5bb2-11ea-89e0-387c6a7d5d51.PNG)

how to fix this problem?

Thanks

**Comment by enesccinar** [comment]
same problem. In my case, some of the custom URLs are also duplicated.

Laravel 5.6

**Comment by engrasadullah97** [comment]
same problem in laravel 6 and some url duplicated with and with out slash.
how to fix

**Comment by leandroruel** [comment]
uh... seems like they're not gonna fix it so soon, i'm gonna check if and maybe send a PR
