### ISSUE TITLE
Generate sitemap without <priority> and <changefreq> parameters

### ISSUE THREAD

**Issue by DiplNext** [spatie/laravel-sitemap#297]
Can I generate sitemap without <priority> and <changefreq> parameters ?

**Comment by jtrod** [comment]
Yes, you still need to use the methods, but with these parameters:              

`$sitemap ->setChangeFrequency('')->setPriority(0))`

**Comment by royduin** [comment]
See: https://support.google.com/webmasters/answer/183668?hl=en

> Google ignores `<priority>` and `<changefreq>` values, so don't bother adding them.

Maybe it should be removed from the package.

**Comment by freekmurze** [comment]
I'd accept a PR that removes them from them package.
