### ISSUE TITLE
[Help wanted] Can't use modifiers?

### ISSUE THREAD

**Issue by jpmurray** [spatie/laravel-sitemap#30]
Using the package (1.0.0) as so

```
use Spatie\Sitemap\Sitemap;
use Spatie\Sitemap\Tags\Url;
$sitemap = Sitemap::create()
            ->add(
                Url::create('/')
                ->changeFrequency(Url::CHANGE_FREQUENCY_ALWAYS)
            );
```

Will result in in the following error: `Call to undefined method Spatie\Sitemap\Tags\Url::changeFrequency()`.

Same occur with `priority()` and `lastModificationDate()`. I'm obviously doing something wrong, but ... What?

**Comment by sebastiandedeyne** [comment]
Looks like their are some errors in the docs concerning method names, gonna fix them now.

The correct ones are `setChangeFrequency`, `setPriority` and `setLastModificationDate`.

**Comment by jpmurray** [comment]
Ugh. I always feel stupid not to have dug the source code in those case, but hey, at least that makes people realize small errors in the docs I guess ;-) Thanks!

**Comment by freekmurze** [comment]
Yea, sorry for those errors. Mostly caused by writing the readme and still refactoring things after that. 

Will give it some more attention when working on future packages.

**Comment by jpmurray** [comment]
If you want a proofreader, give me a shout ;-) I usually can't really contribute code wise, but I feel like I'm good at following the readmes and finding quirks 😆
