### ISSUE TITLE
Multiple domain names diffrect extensions

### ISSUE THREAD

**Issue by MitchBred** [spatie/laravel-sitemap#300]
Hi,

I have two domains with diffrent extensions (domain alias).
How can i use the laravel sitemap?

Thanks.

**Comment by Egzonrexhepi** [comment]
I think you have to create two different sitemaps,

`$firstDomain= SitemapGenerator::create($baseUrl)->getSitemap();`
`$secondDomain= SitemapGenerator::create($baseUrl)->getSitemap();`

and then for each domains add their url-s with:
`$firstDomain->add($url)`
`$secondDomain->add($url)`

Also dont forget to write them to seperate files
`$firstDomain->writeToFile('first_sitemap.xml')`
`$secondDomain->writeToFile('second_doman.xml')`
