### ISSUE TITLE
Stuck with the default sitemap page

### ISSUE THREAD

**Issue by sadiqodho** [spatie/laravel-sitemap#303]
When I install this page, I just wanted to use but not found my required things in it, Then I remove package from it. it is deleted from vendor file whole package. but the strange thing is still www.example.com/sitemap.xml shows same page where i stuck.. What a strange.. Can you please tell me what should i do know to remove complete your package functionality from my project.

**Comment by freekmurze** [comment]
There isn't anything specific you need to do besides remove the package from `composer.json`. Make sure to refresh any caches on production environments too.
