### ISSUE TITLE
Remove urls from sitemap

### ISSUE THREAD

**Issue by MrMooky** [spatie/laravel-sitemap#304]
When a Model gets deleted I would want the sitemap to be updated, reflecting the entry that has been deleted. So basically something like this:

`SitemapGenerator::create('https://igotcha.de')->getSitemap()->remove(Url::create('/'.$category->slug.'/'.$slug)->writeToFile(public_path('sitemap.xml'));`

So yeah, `remove` or `delete` instead of `add`. How can I accomplish that?

**Comment by freekmurze** [comment]
I'd accept a PR that adds this to the package.

**Comment by finex** [comment]
Hi, has this issue been closed because the feature has been added? thanks! :-)
