### ISSUE TITLE
Not work on laravel 7

### ISSUE THREAD

**Issue by ninacoder-info** [spatie/laravel-sitemap#306]
Laravel 5 and 6 is fine but laravel 7 getting this error

Call to undefined method stdClass::getType() (View: /vendor/spatie/laravel-sitemap/resources/views/sitemap.blade.php)

>         Sitemap::create()

            ->add(Url::create('/home')
                ->setLastModificationDate(Carbon::yesterday())
                ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
                ->setPriority(0.1))

            ->writeToFile(public_path('sitemap.xml'));

**Comment by freekmurze** [comment]
Our testsuite indicates that the package works fine on Laravel 7, so the error must be caused by something specific to your app.

Please submit a failing test for us to fix if you think the package is in error.
