### ISSUE TITLE
Should provide $concurrency in config file for better behavior of crawler!

### ISSUE THREAD

**Issue by minhtu-cloudtek** [spatie/laravel-sitemap#314]
Hi dev master,

Your package is good, I've used it for a long time but the crawler sometimes makes some server full-load because of high concurrency (the number of page it crawl/time). Providing $concurrency in config file should be a good solution to help user adjust crawler behavior better.

Thanks!

**Comment by freekmurze** [comment]
Feel free to create a PR for that.

Right now you can alter the concurrency like this:

```php
SitemapGenerator::create('https://example.com')
    ->configureCrawler(function (Crawler $crawler) {
        $crawler->setConcurrency(1) //now all urls will be crawled one by one
    })
    ->writeToFile($path);
```
