### ISSUE TITLE
Removing storage folder from sitemap.xml

### ISSUE THREAD

**Issue by manshu** [spatie/laravel-sitemap#316]
I've been using this package. I've no issues with the package itself. I am seeing issue with /storage/ path being crawled too. How should i remove that from the sitemap.xml

**Comment by freekmurze** [comment]
This package will only crawl links that are public. In normal circumstances `/storage` is not exposed publicly. 

You can use a crawl profile to filter out unwanted links:

https://github.com/spatie/laravel-sitemap#define-a-custom-crawl-profile
