### ISSUE TITLE
In-consistence in sitemap.xml

### ISSUE THREAD

**Issue by charanjeet007** [spatie/laravel-sitemap#318]
It generate sitemap successfully, But some times it generate complete url and some time it miss most of them.
It should be consistence

```
public function sitemap()
{
        SitemapGenerator::create('https://www.example.com')
        ->writeToFile('sitemap.xml');
        return response()->json(array('success' => true));
}
```
Above is example of that,
Any Idea???

**Comment by freekmurze** [comment]
No idea, probably your server responds something differently each time.
