### ISSUE TITLE
[PROPOSAL] Update sitemap on Google Search Console

### ISSUE THREAD

**Issue by michelecurletta** [spatie/laravel-sitemap#32]
What do you think about adding an API call in order to force the sitemap update at the end of its generation process?
There are very [useful API](https://developers.google.com/webmaster-tools/v3/#Sitemaps) provided by Google.

**Comment by freekmurze** [comment]
I'd accept a now breaking PR with tests that adds this to the package.

**Comment by ctf0** [comment]
@michelecurletta doesnt this help https://support.google.com/webmasters/answer/183668?hl=en&ref_topic=4581190#addsitemap ?

**Comment by michelecurletta** [comment]
@ctf0 with your solution the sitemap update is not automatic right after the sitemap generation

**Comment by ctf0** [comment]
the reason i asked because am after the same thing, and creating the Google Search Console requires more work than just creating a curl req to the link in the docs https://developers.google.com/webmaster-tools/v3/sitemaps/submit

**Comment by freekmurze** [comment]
Submitting the sitemap is out of scope of this package. 

If you want this, I suggest you code it up in a package of your own.
