### ISSUE TITLE
Laravel 5.2?

### ISSUE THREAD

**Issue by pbernim** [spatie/laravel-sitemap#33]
I cannot install laravel-sitemap on Laravel 5.2

I get these errors:

Problem 1                                                                               
  - Installation request for spatie/laravel-sitemap ^1.0 -> satisfiable by spatie/larave
sitemap[1.0.0].                                                                         
  - Conclusion: remove laravel/framework v5.2.45                                        
  - Conclusion: don't install laravel/framework v5.2.45                                 
  - spatie/laravel-sitemap 1.0.0 requires illuminate/support ~5.3.0 -> satisfiable by il
minate/support[v5.3.0, v5.3.4].                                                         
  - don't install illuminate/support v5.3.0|don't install laravel/framework v5.2.45     
  - don't install illuminate/support v5.3.4|don't install laravel/framework v5.2.45     
  - Installation request for laravel/framework (locked at v5.2.45, required as 5.2.*) ->
atisfiable by laravel/framework[v5.2.45].

**Comment by freekmurze** [comment]
This package requires Laravel 5.3

**Comment by parsa-script** [comment]
i have same issue in 5.5 

    - Installation request for spatie/laravel-sitemap ^5.2 -> satisfiable by spatie/laravel-sitemap[5.2.0].
