### ISSUE TITLE
create a sitemap manually with custom hostname

### ISSUE THREAD

**Issue by MehdiAghighi** [spatie/laravel-sitemap#331]
i want to create a sitemap with a custom hostname but `Sitemap` class doesn't have an argument to give the hostname

so i used the function below at the top of sitemap creation code:
```php
resolve('url')->forceRootUrl("https://linom.is");
```

i don't know why but is uses `http` protocol instead of `https` even though i gave https to the function !

**Comment by lovecoding-git** [comment]
hi @MehdiAghighi 
Did you solve this issue?

**Comment by lovecoding-git** [comment]
@MehdiAghighi  

Try this?

```
        \URL::forceRootUrl("https://linom.is");
        \URL::forceScheme('https');
```
