### ISSUE TITLE
Should Laravel be a composer requirement?

### ISSUE THREAD

**Issue by thomasmoors** [spatie/laravel-sitemap#334]
As this package only works with Laravel (and Lumen probably), using the [app global helper from the framework](https://github.com/spatie/laravel-sitemap/blob/master/src/SitemapGenerator.php#L49) for example. Shouldn't it be a requirement in https://github.com/spatie/laravel-sitemap/blob/master/composer.json? That way it could work "standalone" (having Laravel as a dependency).

**Comment by freekmurze** [comment]
I think requiring laravel/support is enough for now.
