### ISSUE TITLE
Incorrect URLs being generated

### ISSUE THREAD

**Issue by kadnan** [spatie/laravel-sitemap#335]
On running the command `php artisan sitemap:generate` from command line it is generating wrong URLs like below:

```
<url>
        <loc>http://example.com/product/6/privacy-policy/</loc>
        <lastmod>2020-10-11T09:21:37+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
```
Though in reality, the only URL exists is `http://example.com/privacy-policy/`. The same is with `sitemap.xml` URL. In reality, it should not be included at all.

**Comment by freekmurze** [comment]
Our tests indicate that the crawler is running correctly. Probably you have that `http://example.com/product/6/privacy-policy/` link somewhere on your site, because the crawler can't just come up with that.

If you think the package is in error, please PR a failing test for me to look at.
