### ISSUE TITLE
Uncaught Error: Call to undefined function Spatie\Sitemap\view()

### ISSUE THREAD

**Issue by DRN88** [spatie/laravel-sitemap#337]
Hi.

Fresh install with composer. I have a standalone simple php project.

This is the error what I get:

`
PHP Fatal error:  Uncaught Error: Call to undefined function Spatie\Sitemap\view() in /opt/productintegrator/vendor/spatie/laravel-sitemap/src/Sitemap.php:62
Stack trace:
#0 /opt/productintegrator/vendor/spatie/laravel-sitemap/src/Sitemap.php(69): Spatie\Sitemap\Sitemap->render()
#1 /opt/productintegrator/solution/outgoing/shoprenter/createSitemaps.php(59): Spatie\Sitemap\Sitemap->writeToFile('/opt/productint...')
#2 {main}
  thrown in /opt/productintegrator/vendor/spatie/laravel-sitemap/src/Sitemap.php on line 62
`

**Comment by freekmurze** [comment]
strange, the `view` functions comes from Laravel, not sure why it isn't working for you. Or testsuite indicates that it is working.

If you think the package is in error, feel free to submit a PR.
