### ISSUE TITLE
Laravel 8 composer installation failure - guzzle 7 x guzzle 6

### ISSUE THREAD

**Issue by kelcampus** [spatie/laravel-sitemap#340]
Hi,

when trying to install on laravel 8.13.0 there is a dependency conflict with guzzle considering that laravel 8 requires guzzle 7.

I tried to install with the command: **composer require spatie/laravel-sitemap:^5.8**

> Your requirements could not be resolved to an installable set of packages
>  Problem 1
>     - Installation request for symfony/console (locked at v5.1.8) -> satisfiable by symfony/console[v5.1.8].
>     - Installation request for spatie/laravel-sitemap ^5.8 -> satisfiable by spatie/laravel-sitemap[5.8.0].
>     - Installation request for symfony/process (locked at v5.1.8) -> satisfiable by symfony/process[v5.1.8].
>     - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
>     - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
>     - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
>     - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
>     - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].

Is it a bug? or can i solve it in another way?

Thanks!

**Comment by Jurre-nl** [comment]
Same issue here!

**Comment by kelcampus** [comment]
I developed an internal solution in the company where I work.
So, I don't need that package anymore.
:)
