### ISSUE TITLE
Generate sitemap on shared hosting got error

### ISSUE THREAD

**Issue by RiyanAmanda** [spatie/laravel-sitemap#346]
Everything is work in local machine, but on shared hosting i got error like so

  Argument 1 passed to Spatie\Crawler\Crawler::create() must be of the type array, null given, called in /home/u289837273/domains/internetpalembang.net/MyRepublicPalemb
ang/vendor/spatie/laravel-sitemap/src/SitemapServiceProvider.php on line 25

  at vendor/spatie/crawler/src/Crawler.php:96
     92▕             'User-Agent' => self::DEFAULT_USER_AGENT,
     93▕         ],
     94▕     ];
     95▕ 
  ➜  96▕     public static function create(array $clientOptions = []): Crawler
     97▕     {
     98▕         $clientOptions = (count($clientOptions))
     99▕             ? $clientOptions
    100▕             : static::$defaultClientOptions;

      +15 vendor frames
  16  app/Console/Commands/GenerateSitemap.php:32
      Spatie\Sitemap\SitemapGenerator::create("http://internetpalembang.net") 

      +13 vendor frames
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

anyone can help?

**Comment by LambdaDigamma** [comment]
Did you already try running `php artisan optimize`. 
This resolved the issue at least for me.

**Comment by RiyanAmanda** [comment]
its work @LambdaDigamma , thanks for help
