### ISSUE TITLE
Empty sitemap 

### ISSUE THREAD

**Issue by neha023** [spatie/laravel-sitemap#348]
Hi,

I have below code to generate the sitemap:

```
 SitemapGenerator::create('http://host-ip/test/public/')
        ->maxTagsPerSitemap(20000)
        ->configureCrawler(function (Crawler $crawler) {
             $crawler->setMaximumDepth(3);
         })
        ->configureCrawler(function (Crawler $crawler) {
            $crawler->ignoreRobots();
        })
        /*->shouldCrawl(function (UriInterface $url) {
               \Illuminate\Support\Facades\Log::debug('should crawl', compact('url'));
               return true;
         })
         ->hasCrawled(function (Url $url) {
              \Illuminate\Support\Facades\Log::debug('has crawled', compact('url'));
               // ....
          })*/
        ->writeToFile(public_path('sitemap.xml'));
```

It is showing me empty sitemap :
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
</urlset>
```

I matched the url in .env and config\app.php but nothing is working for me.

**Comment by Hyleeh** [comment]
Having the same issue without any errors

**Comment by neha023** [comment]
Hi,

I am testing it on my uat server and  below is the url format:
 SitemapGenerator::create('http://ip/projectname/public/')


Can you please help me to resolve this.

**Comment by bridgeyuwa** [comment]
getting EMPTY xml too.

**Comment by rapidtechsolutions** [comment]
same here.

**Comment by mnvx** [comment]
In my case sitemap is not empty on local environment and empty on stage.
Locally generation takes less than second. On stage about a minute.

**Comment by e-hop** [comment]
Same problem
![image](https://user-images.githubusercontent.com/62304175/135677527-11e40955-2b03-41e3-84b9-a27c01e00deb.png)
