### ISSUE TITLE
Installation failed with guzzlehttp requirement conflict

### ISSUE THREAD

**Issue by asimuzzaman** [spatie/laravel-sitemap#357]
While installing **laravel-sitemap** (_version: 5.9_) using composer, installation failed with **guzzlehttp** dependency error. Following was the error message:

``` Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spatie/laravel-sitemap 5.9.1 requires guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0] but these conflict with your requirements or minimum-stability.
    - spatie/laravel-sitemap 5.9.0 requires guzzlehttp/guzzle ^7.2 -> satisfiable by guzzlehttp/guzzle[7.2.0] but these conflict with your requirements or minimum-stability.
    - Installation request for spatie/laravel-sitemap ^5.9 -> satisfiable by spatie/laravel-sitemap[5.9.0, 5.9.1].


Installation failed, reverting ./composer.json to its original content.
```

_Using laravel 6.0._

**Comment by TheArKaID** [comment]
I have the same problem here, using Laravel 8.0 and guzzlehttp/guzzle ^7.0.1. I thought the solution is updating guzzlehttp/guzzle to 7.2.0, but there are some change and deprecation in the guzzlehttp/guzzle [CHANGELOG](https://github.com/guzzle/guzzle/blob/7.2.0/CHANGELOG.md) and I don't know how it impact Laravel.
For now, I will skip to use this package, until any response here, maybe.
