### ISSUE TITLE
Call to undefined method Spatie\Crawler\Crawler::setMaximumCrawlCount()

### ISSUE THREAD

**Issue by ToonDG** [spatie/laravel-sitemap#380]
When I use
`SitemapGenerator::create($url)->setMaximumCrawlCount(10)->...`

I get the error:
`Call to undefined method Spatie\Crawler\Crawler::setMaximumCrawlCount()` in `\vendor\spatie\laravel-sitemap\src\SitemapGenerator.php:123`

**Comment by freekmurze** [comment]
The method [does exist](https://github.com/spatie/laravel-sitemap/blob/efc0e4d70f589db25c318e2765a5583feefe05e9/src/SitemapGenerator.php#L65).

**Comment by ToonDG** [comment]
Yes, but the method is called on the Crawler, not on SitemapGenerator:
https://github.com/spatie/laravel-sitemap/blob/efc0e4d70f589db25c318e2765a5583feefe05e9/src/SitemapGenerator.php#L117

**Comment by freekmurze** [comment]
Try this

```
php
SitemapGenerator::create('https://example.com')
    ->configureCrawler(function (Crawler $crawler) {
        $crawler->setMaximumCrawlCount(3);
    })
    ->writeToFile($path);
```

**Comment by ToonDG** [comment]
It gives me the same error:

`Error
Call to undefined method Spatie\Crawler\Crawler::setMaximumCrawlCount()`

It works when I use:

```
php
SitemapGenerator::create('https://example.com')
    ->configureCrawler(function (Crawler $crawler) {
            $crawler->setTotalCrawlLimit(3);
    })
    ->writeToFile($path);
```

**Comment by freekmurze** [comment]
Yeah, probably, the API was slightly changes in de new version. Glad you found a solution.
