### ISSUE TITLE
error after 6.0.3 update

### ISSUE THREAD

**Issue by dariocarbone** [spatie/laravel-sitemap#391]
Hi, since 6.0.3 update when launching SitemapGenerator::create method, I've got this error:

Declaration of Spatie\Sitemap\Crawler\Observer::willCrawl(Psr\Http\Message\UriInterface $url) must be compatible with Spatie\Crawler\CrawlObservers\CrawlObserver::willCrawl(Psr\Http\Message\UriInterface $url): void

Downgrading to 6.0.2 release the issue is gone and everything goes fine

**Comment by Nielsvanpach** [comment]
Thanks for letting us now, this should be fixed in 6.0.4

**Comment by dariocarbone** [comment]
Thanks to you, well written and very useful package, by the way!!  :)
