### ISSUE TITLE
v6.0.4: No hint path defined for [laravel-sitemap].

### ISSUE THREAD

**Issue by rgasch** [spatie/laravel-sitemap#393]
I have laravel-sitemap 6.0.4 installed against laravel 8.44.0. My model implements the Sitemapable interface and I have implemented a toSitemapTag() method. When trying to generate a sitemap using this code

            Sitemap::create()
               ->add(JobRepository::getJobsFeed())
               ->writeToFile(public_path('sitemap.xml'));

I get this error: 

    No hint path defined for [laravel-sitemap]. (View: /var/www/jobsite.lan/vendor/spatie/laravel-sitemap/resources/views/sitemap.blade.php)
    in
    Illuminate\View\FileViewFinder::parseNamespaceSegments vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:112

Please advise on how to resolve this.

**Comment by ousid** [comment]
Sometimes you need to clear your cache

```bash
php artisan optimize:clear
```

**Comment by rgasch** [comment]
Thank you, this solved it.
