### ISSUE TITLE
Memory leak on writeToFile 

### ISSUE THREAD

**Issue by Prysis** [spatie/laravel-sitemap#394]
I think there is memory lick on writeToFile but don't know why
I working with big list of links and I separate the sitemap files for decreasing memory using but memory using doesn't decrease
Please check logs and code:
![mem](https://user-images.githubusercontent.com/82970162/120967524-c894d000-c77c-11eb-8580-e9262f03613c.jpg)
![f1](https://user-images.githubusercontent.com/82970162/120967527-c9c5fd00-c77c-11eb-9917-9d6975f234cc.jpg)
![f2](https://user-images.githubusercontent.com/82970162/120967516-c6cb0c80-c77c-11eb-89ff-2f85cef461a8.jpg)

**Comment by Prysis** [comment]
I think I find the problem 
It's not from my code or your library 
It's come from php it self
Maybe This reference can help you solve memory leak
https://www.php.net/manual/en/features.gc.refcounting-basics.php
But for me gc_collect_cycles do nothing

**Comment by arnovanoordt** [comment]
Got the same issue

**Comment by Prysis** [comment]
> Got the same issue. Havn't found a solution yet :(

After 4 day research on php memory debugging and testing every part of code, I  finally find the problem.

It's was not about my code, library or php  

ITS ALL ABOUT LARAVEL
Laravel `view()->render()` keep rendered data in memory [More info!](https://github.com/laravel/framework/issues/31505)
And this library  use Laravel view to render sitemap **(BIG MISTAKE)**

So I edit library to use classic php for rendering sitemap (`$render .= "<loc>".url($tag->url)."</loc>" . PHP_EOL;`)
and everything fine now

I fork and commit my changes after make sure I convert everything currently

Checkout my new scores 💯 
![image](https://user-images.githubusercontent.com/82970162/121219840-5665dd80-c899-11eb-8c60-84c31d8e4b1b.png)

**Comment by Prysis** [comment]
> Got the same issue. Havn't found a solution yet :(

Fix is ready check here: https://github.com/spatie/laravel-sitemap/pull/396/commits/5cd7259e887f0946d7f7793ab00369b45c7d7547

**Comment by arnovanoordt** [comment]
Thanks! I came up with roughly the same solution, but did the rendering outside the Sitemap class so I can just keep the plugin as is.

**Comment by freekmurze** [comment]
This will be handled in #396
