### ISSUE TITLE
Cannot install laravel-sitemap

### ISSUE THREAD

**Issue by teobatman00** [spatie/laravel-sitemap#401]
### Discussed in https://github.com/spatie/laravel-sitemap/discussions/400

<div type='discussions-op-text'>

<sup>Originally posted by **teobatman00** July  4, 2021</sup>
Hello all developers, I would like to install sitemap to laravel before uploading to hosting but I got the problems that could not be resolved. Could anyone help me? 

**Terminal**
`composer require spatie/laravel-sitemap `

**Result**

> spatie/laravel-sitemap[6.0.0, ..., 6.0.2] require spatie/crawler ^5.0 || ^6.0 -> satisfiable by spatie/crawler[5.0.0, 5.0.1, 5.0.2, v5.x-dev, 6.0.0, 6.0.1, 6.0.2, v6.x-dev].
    - spatie/laravel-sitemap[6.0.3, ..., 6.0.4] require spatie/crawler ^5.0 || ^7.0 -> satisfiable by spatie/crawler[5.0.0, 5.0.1, 5.0.2, v5.x-dev, 7.0.0].
    - spatie/crawler[6.0.0, ..., v6.x-dev] require guzzlehttp/psr7 ^1.7 -> found guzzlehttp/psr7[1.7.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - spatie/crawler[5.0.2, ..., v5.x-dev] require guzzlehttp/psr7 ^1.4 -> found guzzlehttp/psr7[1.4.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - spatie/crawler[5.0.0, ..., 5.0.1] require php ^7.4 -> your php version (8.0.6) does not satisfy that requirement.
    - spatie/crawler 7.0.0 requires guzzlehttp/psr7 ^1.8 -> found guzzlehttp/psr7[1.8.0, 1.8.1, 1.8.2, 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires spatie/laravel-sitemap ^6.0 -> satisfiable by spatie/laravel-sitemap[6.0.0, ..., 6.0.4].
 
**This is all the problem**</div>

**Comment by freekmurze** [comment]
Closing as this is a question that belongs in discussions.
