### ISSUE TITLE
Call to undefined method Spatie\Crawler\Crawler::setMaximumCrawlCount()

### ISSUE THREAD

**Issue by o15a3d4l11s2** [spatie/laravel-sitemap#406]
With version 6.0.4 I get the error
```
Call to undefined method Spatie\Crawler\Crawler::setMaximumCrawlCount()
```

It is caused by `vendor/spatie/laravel-sitemap/src/SitemapGenerator.php:117`
```php
if (! is_null($this->maximumCrawlCount)) {
    $this->crawler->setMaximumCrawlCount($this->maximumCrawlCount);
}
```

In reality the `Crawler` class does not have `setMaximumCrawlCount`. It has `setTotalCrawlLimit` which I believe is what should be called.

A simple implementation example that can reproduce the issue:
```php
SitemapGenerator::create(config('app.url'))
    ->setMaximumCrawlCount(50)
    ->writeToFile(public_path('sitemap.xml'));
```

EDIT:

As a proof, here is the commit that removes the method: https://github.com/spatie/crawler/commit/f2c724a0e9343889a99f40c0225738e547442190

I would make a PR, but I am not sure what is your preferred way of handling both v5 and v7, as it is defined in composer that  both versions are supported `"spatie/crawler": "^5.0 || ^7.0"`. This change was made after v5, but I think it would be safe to just change the called method to the correct one?

**Comment by freekmurze** [comment]
Feel free to PR a fix, I'm ok with only supporting ^7.0
