### ISSUE TITLE
Generating Empty File

### ISSUE THREAD

**Issue by asciinip** [spatie/laravel-sitemap#416]
in my laravel website, sitemap worked perfectly in last few days, but now its not working with only my domain, its generating empty file, if i replace another domain with this code its generating sitemap file perfectly, i can access every pages in my website with this domain. Didn't make any changes with my server,  pls help to solve this issue. thanks.

`Route::get('create/sitemap', function () {
    SitemapGenerator::create('https://tosale.lk/')->writeToFile('/domains/tosale.lk/tosale/storage/app/public/sitemap.xml');
});`

**Comment by asciinip** [comment]
> 
> 
> in my laravel website, sitemap worked perfectly in last few days, but now its not working with only my domain, its generating empty file, if i replace another domain with this code its generating sitemap file perfectly, i can access every pages in my website with this domain. Didn't make any changes with my server, pls help to solve this issue. thanks.
> 
> `Route::get('create/sitemap', function () { SitemapGenerator::create('https://tosale.lk/')->writeToFile('/domains/tosale.lk/tosale/storage/app/public/sitemap.xml'); });`

i think i figured out the issue, its with my DNS server .

**Comment by e-hop** [comment]
Having the same issue
![image](https://user-images.githubusercontent.com/62304175/135677380-c5daa0e4-11b1-4e16-9b47-d5181fc6bf39.png)

**Comment by divdax** [comment]
Same here. Any solution?

**Comment by vuletuanbt** [comment]
> Same here. Any solution?

In my case, robots prevent us to crawl pages. So just add `ignoreRobots ` :
```php

SitemapGenerator::create('http://localhost:4020')
    ->configureCrawler(function (Crawler $crawler) {
        $crawler->ignoreRobots();
    })
    ->writeToFile($file);

```
