### ISSUE TITLE
Only homepage is indexed

### ISSUE THREAD

**Issue by schel4ok** [spatie/laravel-sitemap#443]
I ran the sitemap generator in Laravel 8.83.8 and it only indexed the homepage.
I found absolutely same issue posted one year ago by someone else using the default config for the generator, didn't change a thing and get the same result.
That issue was just closed by moderator and moved to discussion without try to help. Few more people reported the same behavoiur, no support and all of them just decided to create sitemap manually.
Maybe this package CANNOT generate a sitemap without having to add urls to it manually?

What I did to reproduce the issue?
```
namespace App\Console\Commands;
use Illuminate\Console\Command;
use Spatie\Sitemap\SitemapGenerator;

class GenerateSitemapCommand extends Command
{

    protected $signature = 'sitemap:generate';
    protected $description = 'Generate the sitemap.';

    public function handle()
    {
        SitemapGenerator::create(config('app.url'))
            ->getSitemap()
            ->writeToFile(public_path('sitemap.xml'));
    }
}
```

in **config/app.php** I have
```
    'url' => env('APP_URL', 'http://localhost'),
```

in **.env** I have
```
APP_URL=http://steklo.schel4ok.tk
```

Then in output xml I seen only homepage
```
<?xml version="1.0" encoding="UTF-8"?>
-<urlset xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
-<url>
<loc>http://steklo.schel4ok.tk/</loc>
<lastmod>2022-04-17T14:38:55+03:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.8</priority>
</url>
</urlset>
```

So I just follow package documentation and it doesn't create sitemap with all links.

**Comment by freekmurze** [comment]
I'm sorry you have troubles using the package. I can assure you that it does work.

Unfortunately I don't have the time to investigate malconfiguration of the package and/or server of your project.

Should you find that the package is in error, feel free to sumbit a PR.
