### ISSUE TITLE
How to make big site maps with over 1 million urls

### ISSUE THREAD

**Issue by deep88** [spatie/laravel-sitemap#45]
i want to create sitemap for a website that has more than 1 million pages.. i want to know how can i create that without effecting the server health. and without getting server timeout error..

**Comment by deep88** [comment]
with existing script i gets server time out error.is it possible to run sitemap in time spans?

**Comment by freekmurze** [comment]
According to the specification a sitemap may contain no more than 50 000 urls. Sitemaps that are larger than this, should be broken up into several smaller sitemaps and a sitemap index.

Currently this package does not have support for sitemap indexes.

I suggest you use an alternative package, such as:

[refinery29/sitemap](https://github.com/refinery29/sitemap)
[RoumenDamianoff/laravel-sitemap](https://github.com/RoumenDamianoff/laravel-sitemap)
[dwightwatson/sitemap](https://github.com/dwightwatson/sitemap)
