### ISSUE TITLE
What about sitemap index?

### ISSUE THREAD

**Issue by ManuDoni** [spatie/laravel-sitemap#50]
Hi,
I think this package will be even more useful if there will be a way to create a sitemap index.

Maybe something that could create the index and the sitemaps at the same time:
```
Spatie\Sitemap\SitemapIndexGenerator::create(['page/to/crawl', 'another/page/to/crawl'])
    ->writeToFile($sitemapPath);
```
or maybe just passing an array of `Spatie\Sitemap\Sitemap` objects to the `create` method.
Just to say a couple of way I (and I hope many others) could use it. 
Thank you!

**Comment by freekmurze** [comment]
This package is meant to be used on rather smallish websites. As I don't need sitemap indexes myself, I haven't added this functionality to the package.

If you want to make a PR please make sure that the implementation is very simple and everything is well tested.

**Comment by ManuDoni** [comment]
Sure, I'm working on it
