### ISSUE TITLE
Sitemap showing HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Siphion01** [spatie/laravel-sitemap#56]
Hi,

After generating a sitemap to https://example.com for instance, the sitemap.xml at it's root URL is showing http://sitemap.xml instead (requiring manual change each time being generated).  

The URL I've provided to the function is "https://example.com".

Any suggestions for mistakes I'm making?  Thank you.

**Comment by freekmurze** [comment]
Could you check the `app.url` in `config/app.php`. Make sure that url starts with `https://`.

If that does not work, reopen this issue and provide some code snippets with which the problem can be recreated.
