### ISSUE TITLE
In readme file, change the "installation" section.

### ISSUE THREAD

**Issue by tes1oner** [spatie/laravel-sitemap#58]
Installation section must be first item in the readme file, 
I was about to leave because **I did not see the installation section.** If I have time tomorrow, I will make an improvement to the repo, it's very cool, I'll try it well to see qlq '

**Comment by sebastiandedeyne** [comment]
I don't think we'd accept a PR that moves the installation section. All our package readmes our set up the same: First a friendly introduction, then the license, then the installation guide. I think this is a sane default and puts the installation section high enough.
