### ISSUE TITLE
Installing on laravel 5.2.45

### ISSUE THREAD

**Issue by swanand09** [spatie/laravel-sitemap#59]
trying version 2.1:
![spatie-sitemap-2_1](https://cloud.githubusercontent.com/assets/4434745/23793326/1b9ff8fa-05a4-11e7-9bcf-e236951907fc.png)

trying version 2.0:
![spatie-sitemap-2_0](https://cloud.githubusercontent.com/assets/4434745/23793334/26d8320a-05a4-11e7-9402-1734c500ad8c.png)

I have eventually try Version 1.* and its ok.  Will I able to use it without any limitations? Thanks

**Comment by swanand09** [comment]
testing version 1.* 

FatalErrorException in `/var/www/html/myproj/vendor/laravel/framework/src/Illuminate/Support/Str.php` line 414: Maximum execution time of 30 seconds exceeded

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this issue?

**Comment by swanand09** [comment]
Hello Sebastian,

I have switched to another package. It has been nearly more than a month
ago. Else, hats for the good job.

Thanks and kind regards,


Swanand
