### ISSUE TITLE
Sitemap not crawling on Laravel 5.4.12

### ISSUE THREAD

**Issue by thepeacock** [spatie/laravel-sitemap#61]
I've installed on laravel 5.4.12 and using the following code to generate the sitemap: 

    try
        {
            $path = 'sitemap.xml';
            SitemapGenerator::create('https://securecyclestore.com')->writeToFile($path);
            return back()->with('alert-success', 'Sitemap updated');
        } catch ( \Exception $e ) {
            return back()->with('alert-danger', 'Something went wrong: ' . $e->getMessage());
        }

Sitemap file is created/updated, but it does not crawl the site.

I have tried with both www. and no www prefix, however it does not make a difference. You can view the sitemap file now and see what is being generated (or what is missing!).

Thanks

**Comment by freekmurze** [comment]
Seems to work fine here. Here's the file that was generated by running

```php
Spatie\Sitemap\SitemapGenerator::create('https://securecyclestore.com')->writeToFile(storage_path('temp/sitemap.xml'));
```

**Comment by thepeacock** [comment]
Thanks, I realised that if I run it from my local dev environment (against my live site) it does in fact work. I am using DigitalOcean/Forge for this server so there must be something up with Forge settings.

Thanks

**Comment by jwalton512** [comment]
I, too, was having this issue in production.  

I ended up having to change the APP_URL in my .env on Forge.  Changing from `http://example.com` to `https://example.com` resolved my issue.

**Comment by thepeacock** [comment]
@jwalton512 thanks for the comment, unfortunately this was not my issue - I already had my .env set to https://
I still have not got it working on my production server and have to run it from my local server.

**Comment by emanmjr** [comment]
Same issue, is there any solution with this problem? Thanks

**Comment by thepeacock** [comment]
No,

 

I still have not managed to get it working from the production site. The way to get it to work was to run it from my local site (pointed at the live server) and then upload the generated sitemap.

 

Not ideal but at least it works

 

 

Ash Prescott
EggShaped IT Ltd
ash@eggshaped.co.uk 
07740347101

**Comment by emanmjr** [comment]
Hi , i try to change my APP_ENV to local, and it works fine, for now i don't know what is the reason , but i keep researching whats the best solution for this problem,, 

Try it if is working on you,.
