### ISSUE TITLE
Crawl Multilingual pages ?

### ISSUE THREAD

**Issue by alanaasmaa** [spatie/laravel-sitemap#62]
Im trying to make the crawler also crawl english pages. 

The only way i get for some reason both languages is 

```
    public function handle()
    {
        SitemapGenerator::create(config('app.url') . '/en')
            ->hasCrawled(function (Url $url) {
                if ($url->segment(1) === 'admin') {
                    return;
                }
                // Cloudflare email protection page
                if ($url->segment(1) === 'cdn-cgi') {
                    return;
                }

                return $url;
            })
            ->writeToFile(public_path('sitemap.xml'));
    }
```

But this way does not include root and pagination for /en paths. Everything else it gets. It seems like a hack and not a safe one to use but it's better than nothing. 

I also tryed to add manually but this didnt seem to work.

**Comment by freekmurze** [comment]
You could create a page that links to all languages of your app and let it crawl starting with that page.
