### ISSUE TITLE
[InvalidArgumentException]   No hint path defined for [laravel-sitemap].

### ISSUE THREAD

**Issue by mkwsra** [spatie/laravel-sitemap#66]
Hey @freekmurze ,

Thanks for all the great work you are doing and the awesome packages.

I ran into this error after a very long process time.
<img width="443" alt="screen shot 2017-05-04 at 9 54 00 am" src="https://cloud.githubusercontent.com/assets/1743919/25693141/341eaa3e-30b0-11e7-945c-46f62f96d846.png">

I have a translated routes and other stuff, so to ease describing, this is my `composer.json` file content @ require section/object:

```
"arcanedev/localization": "^1.0",
        "barryvdh/laravel-ide-helper": "^2.2",
        "baum/baum": "~1.1",
        "christofferok/laravel-emojione": "^1.0",
        "cviebrock/eloquent-sluggable": "^4.2",
        "dimsav/laravel-translatable": "^6.0",
        "doctrine/dbal": "^2.5",
        "guzzlehttp/guzzle": "^6.2",
        "intervention/image": "^2.3",
        "jenssegers/date": "^3.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "predis/predis": "^1.1",
        "pusher/pusher-php-server": "^2.6",
        "rap2hpoutre/laravel-log-viewer": "^0.7.1",
        "spatie/laravel-newsletter": "^3.4",
        "spatie/laravel-sitemap": "^2.2"
```

**Comment by ManuDoni** [comment]
Is `Spatie\Sitemap\SitemapServiceProvider::class` in your providers list?
From the docs:
```
// config/app.php
'providers' => [
    ...
    Spatie\Sitemap\SitemapServiceProvider::class,
];
```

**Comment by mkwsra** [comment]
@ManuDoni I'm so sorry I can't believe that I missed this out, sorry so many hours awake.

It's working perfectly, I appreciate it, and I hope my mistake will help some other guy.

Thanks again.

**Comment by ManuDoni** [comment]
I'm glad to have helped

**Comment by mrchimp** [comment]
> I hope my mistake will help some other guy.

It did.
