### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by warmwhisky** [spatie/laravel-sitemap#68]
I just tried to install but it said I need php7. So I upgraded my xampp to PHP7. Then it said I need spatie/crawler. so I install that, then it says I need Guzzle 6.2 so I install that, then it tell me to uninstall laravel 5.2!

So I guess you dont support 5.2? or is that missing from the docs?

**Comment by sebastiandedeyne** [comment]
Sorry, this package is for Laravel 5.3 and up, as stated in the `composer.json`: https://github.com/spatie/laravel-sitemap/blob/20cb1098b2e5bbfe6fbf4915808b5a6f3974ca1b/composer.json#L20
