### ISSUE TITLE
Only 1 URL

### ISSUE THREAD

**Issue by mikeymatteo** [spatie/laravel-sitemap#73]
I have successfully set this up with a Laravel 5.4.23
When i run php artisan sitemap:generate it successfully creates the sitemap file in the public directory however it only returns 1 item (the index / whatever is specified in the APP_URL env)

```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>http://mydomain.com</loc>
        <lastmod>2017-07-25T20:11:01+00:00</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
</urlset>
```

**Comment by freekmurze** [comment]
Is there a link on `http://mydomain.com` to the other pages that need to be in the sitemap?

**Comment by mikeymatteo** [comment]
Hi, yes.
There are at least 8 in the navbar alone and more throughout the document.
What does the crawler expect to see? Does it require a FQDN as the href? or is `<a href="contact"></a>` sufficient?

**Comment by freekmurze** [comment]
I'm thinking that `contact` should be enough.

Could you try to see if creating a sitemap for another site eg. `https://spatie.be/en` works?

**Comment by mikeymatteo** [comment]
Yes, with the APP_URL set to your address my sitemap is now populated.
I adjusted all of my hrefs to a FQDN as a test with no change.
It's not the fact yours is HTTPS is it?

Does it literally crawl the url for links?

**Comment by freekmurze** [comment]
Yup, it will try to find all the links in your html document. What's the output when your try to curl your page?

**Comment by mikeymatteo** [comment]
Simply curl'ing the domain? for the response head or body?

**Comment by freekmurze** [comment]
The body, just to see what your server returns.

**Comment by mikeymatteo** [comment]
Sent email with details. Didn't want to publicly post it. Thanks.

**Comment by freekmurze** [comment]
Curl response seems good to me. Have you tried changing your links to FQDN?

**Comment by mikeymatteo** [comment]
yes, I've tried both `/contact` and `http://www.mydomain.com/contact` (for example).
Is it possible SSL has anything to do with it, or the lack of (for now) for that matter?

**Comment by mikeymatteo** [comment]
I tried to crawl google.com :)

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://www.google.com/</loc>
    
        <lastmod>2017-07-28T18:43:21+00:00</lastmod>
    
        <changefreq>daily</changefreq>
    
        <priority>0.8</priority>
    </url>
</urlset>

```

**Comment by freekmurze** [comment]
I can't immediately determine why your site isn't being crawled.

Fyi this is the code that finds that links on a page: https://github.com/spatie/crawler/blob/master/src/Crawler.php#L187-L219

**Comment by junkie** [comment]
I had the same problem and discovered that the issue was that `Spatie\Crawler\Crawler` was created with the default option to not allow redirects. I would be nice to be able to pass in options to the crawler but I don't think it's an easy fix.

**Comment by junkie** [comment]
I've made a pull request thats a config file with the crawler options. #75

**Comment by freekmurze** [comment]
Thanks @junkie 
I'll review that PR as soon as I have some time on my hands.

**Comment by freekmurze** [comment]
We'll handle this further in #75

**Comment by bhushangaykawad** [comment]
I have installed laravel 5.7. Just created command as given in the documentation changed app_url to enlight.test .. (i am on windows using laragon). getting same result.. only one url


<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
    <url>
    
    <loc>http://enlight.test/</loc>
        <lastmod>2018-12-19T15:41:45+05:30</lastmod>
        <changefreq>daily</changefreq>
        <priority>0.8</priority>
    </url>
</urlset>

**Comment by Nikil-Ojha** [comment]
Hi @mikeymatteo,
How are you doing, Did you able to find a solution?

**Comment by andyyou** [comment]
Is there any solution seems currently more and more people use Inertia.js. It's will be a problem. I can only add links manually now. If someone have any solution? Thanks

**Comment by livevsonline** [comment]
I could not make it work with inertia.js Laravel application, I also tried setting the `execute_javascript ` config to true
