### ISSUE TITLE
Provide verbose options

### ISSUE THREAD

**Issue by ladhadha** [spatie/laravel-sitemap#76]
Hi @freekmurze, thank your for creating this great Laravel package. I have some trouble here. But still don't have any idea what's wrong. On my local enviroment, the `sitemap.xml` generated completely. But when I run it on my production enviroment, the `sitemap.xml` only contains site root url. There are only just single url generated. 

Can we have a verbose option (`-vvv`) to this package, so it can help us to know whats going wrong?

**Comment by freekmurze** [comment]
If it's easy to add and testable I'd accept a PR that adds some sort of logging.
