### ISSUE TITLE
Call to a member function getPath() on null when using command

### ISSUE THREAD

**Issue by dahabit** [spatie/laravel-sitemap#78]
Hi Freek ,
Thanks for your great packages

I have problem when using commands to generate sitemap , every thing working fine when using routes with the same code

here is my command  example code:

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;
use Spatie\Sitemap\SitemapGenerator;

class GenerateSitemap extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'sitemap:GenerateSitemap';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'GenerateSitemap description';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->info('sitemape generate started..');
        SitemapGenerator::create(config('app.url'))->writeToFile(public_path('sitemap_test.xml'));
    }
}
```

when running `php artisan sitemap:GenerateSitemap`

`[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getPath() on null`

My laravel version is 5.4.32

**Comment by freekmurze** [comment]
That's not too good. Do you perhaps have link on your site that has a blank or no `href`?

**Comment by dahabit** [comment]
I'm testing it on local site may be that's the reason ? 
also I tested it with the value direct without using "config('app.url')" and the same result

**Comment by dahabit** [comment]
Hi , I think The problem from my side i found that there code that override Laravel findNamespacedView method which cause that error when saving  any file inside public folder
