### ISSUE TITLE
Support Illuminate 5.5

### ISSUE THREAD

**Issue by ilvalerione** [spatie/laravel-sitemap#81]
In composer.json file was added autodiscover package capability but required field does not support Illuminate 5.5

**Comment by freekmurze** [comment]
Seems ok to me: https://github.com/spatie/laravel-sitemap/blob/3.0.0/composer.json#L20

Which errors are you getting?
How can I reproduce the problem?

**Comment by ilvalerione** [comment]
Sorry, I was try to update 2.* version. 

It's need 3.*
