### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by gurudlan** [spatie/laravel-sitemap#84]
Hello,

I have PHP 7.1.8v, i install your package via composer (2.4.0v sitemap), but when i start this command " php artisan vendor:publish --provider="Spatie\Sitemap\SitemapServiceProvider" --tag=config " it's okey, published...But when i open config folder i don't see sitemap.php file...Can you help me?

Thanks

**Comment by freekmurze** [comment]
Run `config:clear` and try publishing the assets again.

**Comment by gurudlan** [comment]
Hello,

Thank you for reply, but it's not work... I try delete all cache and optimize and re-run publishing but in config folder don't see sitemap.php

have you any idea?

thanks

**Comment by gurudlan** [comment]
For more information about my laravel app, it's laravel 5.4 and i use your package 2.4.0

**Comment by ammu-17** [comment]
in config folder i didn't see sitemap.php after upload command
