### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by gurudlan** [spatie/laravel-sitemap#85]
Hello,

i have laravel 5.4 app and your package 2.4.0...I follow your installation instruction and install your package via composer. Next i try publish vendor (published succesfully) but in config folder don't see sitemap.php...
In app/providers i haven't Sitemapprovider, and in config/app.php i don't have too...

Hm, can you help me? Have you some idea? I try delete all cache and optimize,but problem don't fix...

Thanks

**Comment by freekmurze** [comment]
Have you tried installing the package in a Vanilla Laravel app?

**Comment by gurudlan** [comment]
No, i need install package to my Lara app...

**Comment by gurudlan** [comment]
Okey, i fix it...I need add " Spatie\Sitemap\SitemapServiceProvider::class " to my config/app.php, next run config:clear and than vendor publish and now it work... YEA !
