### ISSUE TITLE
Problems updating to L 5.4.36

### ISSUE THREAD

**Issue by mmjjb** [spatie/laravel-sitemap#86]
Problem 1
    - Installation request for spatie/laravel-sitemap ^3.0 -> satisfiable by spatie/laravel-sitemap[3.0.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - spatie/laravel-sitemap 3.0.0 requires illuminate/support ~5.5.0 -> satisfiable by illuminate/support[v5.5.0, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36

**Comment by gurudlan** [comment]
Hello,

I think, you need use package 2.4.0 not 3.0 because you have laravel 5.4

**Comment by freekmurze** [comment]
Try this:

```bash
composer require spatie/laravel-sitemap ^2.0
```

**Comment by mmjjb** [comment]
Trying version ^2.0 works!
Strange that using the latest version does not work, so I have to use version 2 instead of 3 because 3 is incompatible?

**Comment by emanmjr** [comment]
Thanks for this topic,
