### ISSUE TITLE
How to add new URL to sitemap without overwrite

### ISSUE THREAD

**Issue by 4sh3** [spatie/laravel-sitemap#89]
How to add new URL to sitemap.xml  file without overwrite

`<?php

  namespace App\Http\Controllers;

  use Illuminate\Http\Request;
  use Spatie\Sitemap\SitemapGenerator;
  use Spatie\Sitemap\Sitemap;
  use Spatie\Sitemap\Tags\Url;
  use Carbon\Carbon;

  class SitemapController extends Controller
  {

	protected $sitemap;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->sitemap = new Sitemap();
    }

    /**
     * Generate the first sitemap of the site
     * @return [type] [description]
     */
    public function generateSitemap(){
    	$this->sitemap
    		->add(Url::create(url('/'))
			->setLastModificationDate(Carbon::now())
			->setChangeFrequency(Url::CHANGE_FREQUENCY_MONTHLY)
			->setPriority(0.9))
    		->writeToFile('sitemap.xml');
    }

    /**
     * With a cronn autoGenerate the sitemap with all Posts
     * @return [type] [https://support.google.com/webmasters/answer/183668?hl=es]
     */
    public function autoGenerateSitemap(){
    	$posts = \App\Post::orderBy('id', 'DESC')->get();
		foreach($posts as $post){
		    $this->sitemap
		    	->add(Url::create(url('/post', str_replace("-", " ", $post->post_title)))
		        ->setLastModificationDate(Carbon::createFromFormat('Y-m-d H:i:s', $post->updated_at))
		        ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
		        ->setPriority(0.8)
		    );
		}
		$this->sitemap->writeToFile('sitemap.xml'); // This is overwriting the code
    }
}`

**Comment by 4sh3** [comment]
I have done this to solve it:

`    public function autoGenerateSitemap(){
    	$this->addIndexLinksToSitemap();
    	$this->addPostLinksToSitemap();
    }

    private function addIndexLinksToSitemap(){
		$this->sitemap
    		->add(Url::create(url('/'))
			->setLastModificationDate(Carbon::now())
			->setChangeFrequency(Url::CHANGE_FREQUENCY_MONTHLY)
			->setPriority(0.9))
    		->writeToFile('sitemap.xml');
    }

    private function addPostLinksToSitemap(){
    	$posts = \App\Post::orderBy('updated_at', 'DESC')->get();
		foreach($posts as $post){
		    $this->sitemap
		    	->add(Url::create(url('/post', str_replace("-", " ", $post->post_title)))
		        ->setLastModificationDate(Carbon::createFromFormat('Y-m-d H:i:s', $post->updated_at))
		        ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
		        ->setPriority(0.8)
		    );
		}
		$this->sitemap->writeToFile('sitemap.xml');
    }`

The post are listed for updated_at but when they are wrote on the .xml file they are unordered, why?

**Comment by freekmurze** [comment]
This is how you can generate a sitemap and add manually add some links to it:

```php
SitemapGenerator::create('https://example.com')
   ->getSitemap()
   ->add(Url::create('/extra-page')
        ->setLastModificationDate(Carbon::yesterday())
        ->setChangeFrequency(Url::CHANGE_FREQUENCY_YEARLY)
        ->setPriority(0.1))

    ->add(...)

    ->writeToFile($path);
```

**Comment by taytus** [comment]
Hello @freekmurze, I still can't make it work. 
Every time I call this method, it overrwrites the previous sitemap.
I'm using V 4.0
```
public function add_pages($pages)
    {

        $res = SitemapGenerator::create('127.0.01:8000')
            ->getSitemap();
        foreach ($pages as $item) {
            $parser_url = "https://some_url.com/";

            $url = $parser_url . $item['property_id'] . "/" . $item['url'];
            $res->add(Url::create($url)->setPriority(0.5));

        }

        $res->writeToFile($this->sitemap_path);
    };
```
