### ISSUE TITLE
Skip tests if testserver is not running

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-sitemap#91]
Not super important but wouldn't we want the build to fail if the test server isn't running? Specifically for Travis: skipping all tests would just make the build pass without being tested at all...

https://github.com/spatie/laravel-sitemap/blob/6f12ae61c3f5ae1ecfa293a50d57012dd2680841/tests/SitemapGeneratorTest.php#L84-L92

**Comment by freekmurze** [comment]
Yeah, the test should contains a check that on travis the test server MUST run.

**Comment by AlexVanderbist** [comment]
Fixed in e8da26152420c2eaec9ed8d6024513433177c562
