### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by it-can** [spatie/laravel-sitemap#95]
Getting this error when updating:

Seems to be tied to the ide-helper package (https://github.com/barryvdh/laravel-ide-helper)
```
php artisan ide-helper:meta
```

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Too few arguments to function Spatie\Sitemap\Crawler\Profile::__construct(), 0 passed in /vendor/spatie/larave
  l-sitemap/src/SitemapServiceProvider.php on line 33 and exactly 1 expected
```

**Comment by patrickcurl** [comment]
Any fix  / solution for this?

**Comment by sebastiandedeyne** [comment]
Looks like this commit broke it, I think we need to bind the `Profile` class differently.

https://github.com/spatie/laravel-sitemap/commit/ab890d2cc595a4fac0afef4d1b691c60bb8d515e

**Comment by freekmurze** [comment]
@it-can could you check if the current master version fixes the issue?

**Comment by it-can** [comment]
@freekmurze the error is gone

**Comment by freekmurze** [comment]
Bugfix is present in the newly tagged version `3.2.1`

**Comment by it-can** [comment]
Thanks!
